# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
#   sqlc-gen-better-python v0.3.1
from __future__ import annotations

__all__: typing.Sequence[str] = (
    "TestInnerPostgresType",
    "TestPostgresType",
)

import msgspec
import typing


class TestInnerPostgresType(msgspec.Struct):
    table_id: int = msgspec.field()
    bool_test: bool = msgspec.field()


class TestPostgresType(msgspec.Struct):
    id: int = msgspec.field()
    serial_test: int = msgspec.field()
