# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
#   sqlc-gen-better-python v0.0.1
from __future__ import annotations

__all__: typing.Sequence[str] = (
    "Author",
)

import dataclasses
import typing


@dataclasses.dataclass()
class Author:
    id: int
    name: str
    bio: typing.Optional[str]
