# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.8.0
# source file: queries_slice.sql
"""Module containing queries from file queries_slice.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "QueryResults",
    "delete_slice_rows",
    "get_first_slice_name",
    "get_slice_row_filtered",
    "get_slice_rows",
    "get_slice_rows_by_name_or_note",
    "get_slice_rows_by_name_or_note_filtered",
    "get_slice_rows_by_notes",
    "insert_slice_row",
)

import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import turso.aio

    type QueryResultsArgsType = int | float | str | memoryview | bytes | collections.abc.Sequence[QueryResultsArgsType] | None

from test.driver_turso_async.dataclass.functions import models


INSERT_SLICE_ROW: typing.Final[str] = """-- name: InsertSliceRow :exec
INSERT INTO test_slice (id, name, note) VALUES (?, ?, ?)
"""

GET_SLICE_ROWS: typing.Final[str] = """-- name: GetSliceRows :many
SELECT id, name, note FROM test_slice WHERE id IN (/*SLICE:ids*/?) ORDER BY id
"""

GET_SLICE_ROW_FILTERED: typing.Final[str] = """-- name: GetSliceRowFiltered :one
SELECT id, name, note FROM test_slice WHERE name = ? AND id IN (/*SLICE:ids*/?) AND id != ? LIMIT 1
"""

GET_SLICE_ROWS_BY_NOTES: typing.Final[str] = """-- name: GetSliceRowsByNotes :many
SELECT id, name, note FROM test_slice WHERE note IN (/*SLICE:notes*/?) ORDER BY id
"""

GET_FIRST_SLICE_NAME: typing.Final[str] = """-- name: GetFirstSliceName :one
SELECT name FROM test_slice WHERE id IN (/*SLICE:ids*/?) OR name IN (/*SLICE:names*/?) ORDER BY id LIMIT 1
"""

GET_SLICE_ROWS_BY_NAME_OR_NOTE: typing.Final[str] = """-- name: GetSliceRowsByNameOrNote :many
SELECT id, name, note FROM test_slice WHERE name IN (/*SLICE:names*/?) OR note IN (/*SLICE:names*/?) ORDER BY id
"""

GET_SLICE_ROWS_BY_NAME_OR_NOTE_FILTERED: typing.Final[str] = """-- name: GetSliceRowsByNameOrNoteFiltered :many
SELECT id, name, note FROM test_slice WHERE name IN (/*SLICE:names*/?) AND id != ? OR note IN (/*SLICE:names*/?) ORDER BY id
"""

DELETE_SLICE_ROWS: typing.Final[str] = """-- name: DeleteSliceRows :execrows
DELETE FROM test_slice WHERE id IN (/*SLICE:ids*/?)
"""


class QueryResults[T]:
    """Helper class that allows both iteration and normal fetching of data from the db."""

    __slots__ = ("_args", "_conn", "_cursor", "_decode_hook", "_sql")

    def __init__(
        self,
        conn: turso.aio.Connection,
        sql: str,
        decode_hook: collections.abc.Callable[[tuple[typing.Any, ...]], T],
        *args: QueryResultsArgsType,
    ) -> None:
        """Initialize the QueryResults instance.

        Args:
            conn:
                The connection object of type `turso.aio.Connection` used to execute queries.
            sql:
                The SQL statement that will be executed when fetching/iterating.
            decode_hook:
                A callback that turns an `tuple[typing.Any, ...]` object into `T` that will be returned.
            *args:
                Arguments that should be sent when executing the sql query.
        """
        self._conn = conn
        self._sql = sql
        self._decode_hook = decode_hook
        self._args = args
        self._cursor: turso.aio.Cursor | None = None

    def __aiter__(self) -> QueryResults[T]:
        """Initialize iteration support for `async for`.

        Returns:
            Self as an asynchronous iterator.
        """
        return self

    def __await__(
        self,
    ) -> collections.abc.Generator[None, None, collections.abc.Sequence[T]]:
        """Allow `await` on the object to return all rows as a fully decoded sequence.

        Returns:
            A sequence of decoded objects of type `T`.
        """

        async def _wrapper() -> collections.abc.Sequence[T]:
            result = await (await self._conn.execute(self._sql, self._args)).fetchall()
            return [self._decode_hook(row) for row in result]

        return _wrapper().__await__()

    async def __anext__(self) -> T:
        """Yield the next item in the query result using a turso.aio cursor.

        Returns:
            The next decoded result of type `T`.

        Raises:
            StopAsyncIteration: When no more records are available.
        """
        if self._cursor is None:
            self._cursor = await self._conn.execute(self._sql, self._args)
        record = await self._cursor.fetchone()
        if record is None:
            self._cursor = None
            raise StopAsyncIteration
        return self._decode_hook(record)


async def insert_slice_row(conn: turso.aio.Connection, *, id_: int, name: str, note: str | None) -> None:
    """Execute SQL query with `name: InsertSliceRow :exec`.

    ```sql
    INSERT INTO test_slice (id, name, note) VALUES (?, ?, ?)
    ```

    Args:
        conn:
            Connection object of type `turso.aio.Connection` used to execute the query.
        id_: int.
        name: str.
        note: str | None.
    """
    await conn.execute(INSERT_SLICE_ROW, (id_, name, note))


def get_slice_rows(conn: turso.aio.Connection, *, ids: collections.abc.Sequence[int]) -> QueryResults[models.TestSlice]:
    """Fetch many from the db using the SQL query with `name: GetSliceRows :many`.

    ```sql
    SELECT id, name, note FROM test_slice WHERE id IN (/*SLICE:ids*/?) ORDER BY id
    ```

    Args:
        conn:
            Connection object of type `turso.aio.Connection` used to execute the query.
        ids: collections.abc.Sequence[int].

    Returns:
        Helper class of type `QueryResults[models.TestSlice]` that allows both iteration and normal fetching of data from the db.
    """

    def _decode_hook(row: tuple[typing.Any, ...]) -> models.TestSlice:
        return models.TestSlice(id_=row[0], name=row[1], note=row[2])

    sql = GET_SLICE_ROWS.replace("/*SLICE:ids*/?", ",".join("?" * len(ids)) or "NULL", 1)
    return QueryResults(conn, sql, _decode_hook, *ids)


async def get_slice_row_filtered(conn: turso.aio.Connection, *, name: str, ids: collections.abc.Sequence[int], id_: int) -> models.TestSlice | None:
    """Fetch one from the db using the SQL query with `name: GetSliceRowFiltered :one`.

    ```sql
    SELECT id, name, note FROM test_slice WHERE name = ? AND id IN (/*SLICE:ids*/?) AND id != ? LIMIT 1
    ```

    Args:
        conn:
            Connection object of type `turso.aio.Connection` used to execute the query.
        name: str.
        ids: collections.abc.Sequence[int].
        id_: int.

    Returns:
        Result of type `models.TestSlice` fetched from the db. Will be `None` if not found.
    """
    sql = GET_SLICE_ROW_FILTERED.replace("/*SLICE:ids*/?", ",".join("?" * len(ids)) or "NULL", 1)
    row = await (await conn.execute(sql, (name, *ids, id_))).fetchone()
    if row is None:
        return None
    return models.TestSlice(id_=row[0], name=row[1], note=row[2])


def get_slice_rows_by_notes(conn: turso.aio.Connection, *, notes: collections.abc.Sequence[str]) -> QueryResults[models.TestSlice]:
    """Fetch many from the db using the SQL query with `name: GetSliceRowsByNotes :many`.

    ```sql
    SELECT id, name, note FROM test_slice WHERE note IN (/*SLICE:notes*/?) ORDER BY id
    ```

    Args:
        conn:
            Connection object of type `turso.aio.Connection` used to execute the query.
        notes: collections.abc.Sequence[str].

    Returns:
        Helper class of type `QueryResults[models.TestSlice]` that allows both iteration and normal fetching of data from the db.
    """

    def _decode_hook(row: tuple[typing.Any, ...]) -> models.TestSlice:
        return models.TestSlice(id_=row[0], name=row[1], note=row[2])

    sql = GET_SLICE_ROWS_BY_NOTES.replace("/*SLICE:notes*/?", ",".join("?" * len(notes)) or "NULL", 1)
    return QueryResults(conn, sql, _decode_hook, *notes)


async def get_first_slice_name(conn: turso.aio.Connection, *, ids: collections.abc.Sequence[int], names: collections.abc.Sequence[str]) -> str | None:
    """Fetch one from the db using the SQL query with `name: GetFirstSliceName :one`.

    ```sql
    SELECT name FROM test_slice WHERE id IN (/*SLICE:ids*/?) OR name IN (/*SLICE:names*/?) ORDER BY id LIMIT 1
    ```

    Args:
        conn:
            Connection object of type `turso.aio.Connection` used to execute the query.
        ids: collections.abc.Sequence[int].
        names: collections.abc.Sequence[str].

    Returns:
        Result of type `str` fetched from the db. Will be `None` if not found.
    """
    sql = GET_FIRST_SLICE_NAME.replace("/*SLICE:ids*/?", ",".join("?" * len(ids)) or "NULL", 1)
    sql = sql.replace("/*SLICE:names*/?", ",".join("?" * len(names)) or "NULL", 1)
    row = await (await conn.execute(sql, (*ids, *names))).fetchone()
    if row is None:
        return None
    return row[0]


def get_slice_rows_by_name_or_note(conn: turso.aio.Connection, *, names: collections.abc.Sequence[str]) -> QueryResults[models.TestSlice]:
    """Fetch many from the db using the SQL query with `name: GetSliceRowsByNameOrNote :many`.

    ```sql
    SELECT id, name, note FROM test_slice WHERE name IN (/*SLICE:names*/?) OR note IN (/*SLICE:names*/?) ORDER BY id
    ```

    Args:
        conn:
            Connection object of type `turso.aio.Connection` used to execute the query.
        names: collections.abc.Sequence[str].

    Returns:
        Helper class of type `QueryResults[models.TestSlice]` that allows both iteration and normal fetching of data from the db.
    """

    def _decode_hook(row: tuple[typing.Any, ...]) -> models.TestSlice:
        return models.TestSlice(id_=row[0], name=row[1], note=row[2])

    sql = GET_SLICE_ROWS_BY_NAME_OR_NOTE.replace("/*SLICE:names*/?", ",".join("?" * len(names)) or "NULL")
    return QueryResults(conn, sql, _decode_hook, *names, *names)


def get_slice_rows_by_name_or_note_filtered(conn: turso.aio.Connection, *, names: collections.abc.Sequence[str], id_: int) -> QueryResults[models.TestSlice]:
    """Fetch many from the db using the SQL query with `name: GetSliceRowsByNameOrNoteFiltered :many`.

    ```sql
    SELECT id, name, note FROM test_slice WHERE name IN (/*SLICE:names*/?) AND id != ? OR note IN (/*SLICE:names*/?) ORDER BY id
    ```

    Args:
        conn:
            Connection object of type `turso.aio.Connection` used to execute the query.
        names: collections.abc.Sequence[str].
        id_: int.

    Returns:
        Helper class of type `QueryResults[models.TestSlice]` that allows both iteration and normal fetching of data from the db.
    """

    def _decode_hook(row: tuple[typing.Any, ...]) -> models.TestSlice:
        return models.TestSlice(id_=row[0], name=row[1], note=row[2])

    sql = GET_SLICE_ROWS_BY_NAME_OR_NOTE_FILTERED.replace("/*SLICE:names*/?", ",".join("?" * len(names)) or "NULL")
    return QueryResults(conn, sql, _decode_hook, *names, id_, *names)


async def delete_slice_rows(conn: turso.aio.Connection, *, ids: collections.abc.Sequence[int]) -> int:
    """Execute SQL query with `name: DeleteSliceRows :execrows` and return the number of affected rows.

    ```sql
    DELETE FROM test_slice WHERE id IN (/*SLICE:ids*/?)
    ```

    Args:
        conn:
            Connection object of type `turso.aio.Connection` used to execute the query.
        ids: collections.abc.Sequence[int].

    Returns:
        The number (`int`) of affected rows. This will be 0 for queries like `CREATE TABLE`.
    """
    sql = DELETE_SLICE_ROWS.replace("/*SLICE:ids*/?", ",".join("?" * len(ids)) or "NULL", 1)
    return (await conn.execute(sql, (*ids,))).rowcount
