# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.6.0
# source file: queries_enum_override.sql
"""Module containing queries from file queries_enum_override.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "QueriesEnumOverride",
    "QueryResults",
)

import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import psycopg
    import psycopg.rows

    type QueryResultsArgsType = int | float | str | memoryview | collections.abc.Sequence[QueryResultsArgsType] | None

    type ConnectionLike = psycopg.Connection[psycopg.rows.TupleRow]

from test.driver_psycopg_sync.attrs.classes import enums
from test.driver_psycopg_sync.attrs.classes import models


INSERT_ENUM_OVERRIDE: typing.Final[typing.LiteralString] = """-- name: InsertEnumOverride :exec
INSERT INTO test_enum_override (id, mood_test) VALUES (%(p1)s, %(p2)s)
"""

GET_ENUM_OVERRIDE_MOOD: typing.Final[typing.LiteralString] = """-- name: GetEnumOverrideMood :one
SELECT mood_test FROM test_enum_override WHERE id = %(p1)s
"""

LIST_ENUM_OVERRIDE_BY_IDS: typing.Final[typing.LiteralString] = """-- name: ListEnumOverrideByIds :many
SELECT id, mood_test FROM test_enum_override WHERE id = ANY(%(p1)s::int[])
"""

COUNT_ENUM_OVERRIDE_BY_MOODS: typing.Final[typing.LiteralString] = """-- name: CountEnumOverrideByMoods :one
SELECT count(*) FROM test_enum_override WHERE mood_test = ANY(%(p1)s::test_mood[])
"""


class QueryResults[T]:
    """Helper class that allows both iteration and normal fetching of data from the db.

    Parameters
    ----------
    conn
        The connection object of type `ConnectionLike` used to execute queries.
    sql
        The SQL statement that will be executed when fetching/iterating.
    decode_hook
        A callback that turns an `psycopg.rows.TupleRow` object into `T` that will be returned.
    params
        Named arguments that should be sent when executing the sql query.

    """

    __slots__ = ("_conn", "_cursor", "_decode_hook", "_iterator", "_params", "_sql")

    def __init__(
        self,
        conn: ConnectionLike,
        sql: typing.LiteralString,
        decode_hook: collections.abc.Callable[[psycopg.rows.TupleRow], T],
        params: dict[str, QueryResultsArgsType] | None = None,
    ) -> None:
        """Initialize the QueryResults instance."""
        self._conn = conn
        self._sql: typing.LiteralString = sql
        self._decode_hook = decode_hook
        self._params = params
        self._cursor: psycopg.Cursor[psycopg.rows.TupleRow] | None = None
        self._iterator: collections.abc.Iterator[psycopg.rows.TupleRow] | None = None

    def __iter__(self) -> QueryResults[T]:
        """Initialize iteration support.

        Returns
        -------
        QueryResults[T]
            Self as an iterator.
        """
        return self

    def __call__(
        self,
    ) -> collections.abc.Sequence[T]:
        """Allow calling the object to return all rows as a fully decoded sequence.

        Returns
        -------
        collections.abc.Sequence[T]
            A sequence of decoded objects of type `T`.
        """
        result = self._conn.execute(self._sql, self._params).fetchall()
        return [self._decode_hook(row) for row in result]

    def __next__(self) -> T:
        """Yield the next item in the query result using a psycopg cursor.

        Returns
        -------
        T
            The next decoded result.

        Raises
        ------
        StopIteration
            When no more records are available.
        """
        if self._cursor is None or self._iterator is None:
            self._cursor = self._conn.execute(self._sql, self._params)
            self._iterator = self._cursor.__iter__()
        try:
            record = self._iterator.__next__()
        except StopIteration:
            self._cursor = None
            self._iterator = None
            raise
        return self._decode_hook(record)


class QueriesEnumOverride:
    """Queries from file queries_enum_override.sql.

    Parameters
    ----------
    conn : ConnectionLike
        The connection object used to execute queries.

    """

    __slots__ = ("_conn",)

    def __init__(self, conn: ConnectionLike) -> None:
        """Initialize the instance using the connection."""
        self._conn = conn

    @property
    def conn(self) -> ConnectionLike:
        """Connection object used to make queries.

        Returns
        -------
        ConnectionLike

        """
        return self._conn

    def insert_enum_override(self, *, id_: int, mood_test: str) -> None:
        """Execute SQL query with `name: InsertEnumOverride :exec`.

        ```sql
        INSERT INTO test_enum_override (id, mood_test) VALUES (%(p1)s, %(p2)s)
        ```

        Parameters
        ----------
        id_ : int
        mood_test : str

        """
        self._conn.execute(INSERT_ENUM_OVERRIDE, {"p1": id_, "p2": enums.TestMood(mood_test)})

    def get_enum_override_mood(self, *, id_: int) -> str | None:
        """Fetch one from the db using the SQL query with `name: GetEnumOverrideMood :one`.

        ```sql
        SELECT mood_test FROM test_enum_override WHERE id = %(p1)s
        ```

        Parameters
        ----------
        id_ : int

        Returns
        -------
        str
            Result fetched from the db. Will be `None` if not found.

        """
        row = self._conn.execute(GET_ENUM_OVERRIDE_MOOD, {"p1": id_}).fetchone()
        if row is None:
            return None
        return str(row[0])

    def list_enum_override_by_ids(self, *, dollar_1: collections.abc.Sequence[int]) -> QueryResults[models.TestEnumOverride]:
        """Fetch many from the db using the SQL query with `name: ListEnumOverrideByIds :many`.

        ```sql
        SELECT id, mood_test FROM test_enum_override WHERE id = ANY(%(p1)s::int[])
        ```

        Parameters
        ----------
        dollar_1 : collections.abc.Sequence[int]

        Returns
        -------
        QueryResults[models.TestEnumOverride]
            Helper class that allows both iteration and normal fetching of data from the db.

        """

        def _decode_hook(row: psycopg.rows.TupleRow) -> models.TestEnumOverride:
            return models.TestEnumOverride(id_=row[0], mood_test=str(row[1]))

        return QueryResults(self._conn, LIST_ENUM_OVERRIDE_BY_IDS, _decode_hook, {"p1": list(dollar_1)})

    def count_enum_override_by_moods(self, *, dollar_1: collections.abc.Sequence[enums.TestMood]) -> int | None:
        """Fetch one from the db using the SQL query with `name: CountEnumOverrideByMoods :one`.

        ```sql
        SELECT count(*) FROM test_enum_override WHERE mood_test = ANY(%(p1)s::test_mood[])
        ```

        Parameters
        ----------
        dollar_1 : collections.abc.Sequence[enums.TestMood]

        Returns
        -------
        int
            Result fetched from the db. Will be `None` if not found.

        """
        row = self._conn.execute(COUNT_ENUM_OVERRIDE_BY_MOODS, {"p1": list(dollar_1)}).fetchone()
        if row is None:
            return None
        return row[0]
