# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.6.0
"""Module containing models."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "Model3RdPartyStat",
    "TestEnumOverride",
    "TestEnumType",
    "TestFieldNaming",
    "TestInnerPostgresType",
    "TestInvalidIdentifier",
    "TestPostgresType",
    "TestTypeOverride",
)

import dataclasses
import typing

if typing.TYPE_CHECKING:
    from collections import UserString
    from test.driver_psycopg_sync.dataclass.classes import enums
    import collections.abc
    import datetime
    import decimal
    import uuid


@dataclasses.dataclass()
class Model3RdPartyStat:
    """Model representing Model3RdPartyStat.

    Attributes:
        id_: int
        total: int
    """

    id_: int
    total: int


@dataclasses.dataclass()
class TestEnumOverride:
    """Model representing TestEnumOverride.

    Attributes:
        id_: int
        mood_test: str
    """

    id_: int
    mood_test: str


@dataclasses.dataclass()
class TestEnumType:
    """Model representing TestEnumType.

    Attributes:
        id_: int
        mood: enums.TestMood
        maybe_mood: enums.TestMood | None
    """

    id_: int
    mood: enums.TestMood
    maybe_mood: enums.TestMood | None


@dataclasses.dataclass()
class TestFieldNaming:
    """Model representing TestFieldNaming.

    Attributes:
        id_: int
        outputs: str
    """

    id_: int
    outputs: str


@dataclasses.dataclass()
class TestInnerPostgresType:
    """Model representing TestInnerPostgresType.

    Attributes:
        table_id: int
        serial_test: int | None
        serial4_test: int | None
        bigserial_test: int | None
        smallserial_test: int | None
        int_test: int | None
        bigint_test: int | None
        smallint_test: int | None
        float_test: float | None
        double_precision_test: float | None
        real_test: float | None
        numeric_test: decimal.Decimal | None
        money_test: str | None
        bool_test: bool | None
        json_test: str | None
        jsonb_test: str | None
        bytea_test: memoryview | None
        date_test: datetime.date | None
        time_test: datetime.time | None
        timetz_test: datetime.time | None
        timestamp_test: datetime.datetime | None
        timestamptz_test: datetime.datetime | None
        interval_test: datetime.timedelta | None
        text_test: str | None
        varchar_test: str | None
        bpchar_test: str | None
        char_test: str | None
        citext_test: str | None
        uuid_test: uuid.UUID | None
        inet_test: str | None
        cidr_test: str | None
        macaddr_test: str | None
        macaddr8_test: str | None
        ltree_test: str | None
        lquery_test: str | None
        ltxtquery_test: str | None
    """

    table_id: int
    serial_test: int | None
    serial4_test: int | None
    bigserial_test: int | None
    smallserial_test: int | None
    int_test: int | None
    bigint_test: int | None
    smallint_test: int | None
    float_test: float | None
    double_precision_test: float | None
    real_test: float | None
    numeric_test: decimal.Decimal | None
    money_test: str | None
    bool_test: bool | None
    json_test: str | None
    jsonb_test: str | None
    bytea_test: memoryview | None
    date_test: datetime.date | None
    time_test: datetime.time | None
    timetz_test: datetime.time | None
    timestamp_test: datetime.datetime | None
    timestamptz_test: datetime.datetime | None
    interval_test: datetime.timedelta | None
    text_test: str | None
    varchar_test: str | None
    bpchar_test: str | None
    char_test: str | None
    citext_test: str | None
    uuid_test: uuid.UUID | None
    inet_test: str | None
    cidr_test: str | None
    macaddr_test: str | None
    macaddr8_test: str | None
    ltree_test: str | None
    lquery_test: str | None
    ltxtquery_test: str | None


@dataclasses.dataclass()
class TestInvalidIdentifier:
    """Model representing TestInvalidIdentifier.

    Attributes:
        id_: int
        column_3p_: str | None
        new_notes: str
        column__pct: str | None
    """

    id_: int
    column_3p_: str | None
    new_notes: str
    column__pct: str | None


@dataclasses.dataclass()
class TestPostgresType:
    """Model representing TestPostgresType.

    Attributes:
        id_: int
        serial_test: int
        serial4_test: int
        bigserial_test: int
        smallserial_test: int
        int_test: int
        bigint_test: int
        smallint_test: int
        float_test: float
        double_precision_test: float
        real_test: float
        numeric_test: decimal.Decimal
        money_test: str
        bool_test: bool
        json_test: str
        jsonb_test: str
        bytea_test: memoryview
        date_test: datetime.date
        time_test: datetime.time
        timetz_test: datetime.time
        timestamp_test: datetime.datetime
        timestamptz_test: datetime.datetime
        interval_test: datetime.timedelta
        text_test: str
        varchar_test: str
        bpchar_test: str
        char_test: str
        citext_test: str
        uuid_test: uuid.UUID
        inet_test: str
        cidr_test: str
        macaddr_test: str
        macaddr8_test: str
        ltree_test: str
        lquery_test: str
        ltxtquery_test: str
    """

    id_: int
    serial_test: int
    serial4_test: int
    bigserial_test: int
    smallserial_test: int
    int_test: int
    bigint_test: int
    smallint_test: int
    float_test: float
    double_precision_test: float
    real_test: float
    numeric_test: decimal.Decimal
    money_test: str
    bool_test: bool
    json_test: str
    jsonb_test: str
    bytea_test: memoryview
    date_test: datetime.date
    time_test: datetime.time
    timetz_test: datetime.time
    timestamp_test: datetime.datetime
    timestamptz_test: datetime.datetime
    interval_test: datetime.timedelta
    text_test: str
    varchar_test: str
    bpchar_test: str
    char_test: str
    citext_test: str
    uuid_test: uuid.UUID
    inet_test: str
    cidr_test: str
    macaddr_test: str
    macaddr8_test: str
    ltree_test: str
    lquery_test: str
    ltxtquery_test: str


@dataclasses.dataclass()
class TestTypeOverride:
    """Model representing TestTypeOverride.

    Attributes:
        id_: int
        text_test: UserString | None
    """

    id_: int
    text_test: UserString | None
