# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.6.0
# source file: queries_invalid_identifiers.sql
"""Module containing queries from file queries_invalid_identifiers.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "get_invalid_identifiers",
    "get_third_party_stat",
    "insert_invalid_identifiers",
    "insert_third_party_stat",
)

import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import psycopg
    import psycopg.rows

    type ConnectionLike = psycopg.Connection[psycopg.rows.TupleRow]

from test.driver_psycopg_sync.dataclass.functions import models


INSERT_INVALID_IDENTIFIERS: typing.Final[typing.LiteralString] = """-- name: InsertInvalidIdentifiers :exec
INSERT INTO test_invalid_identifiers (id, "3p%%", "new notes") VALUES (%(p1)s, %(p2)s, %(p3)s)
"""

GET_INVALID_IDENTIFIERS: typing.Final[typing.LiteralString] = """-- name: GetInvalidIdentifiers :one
SELECT id, "3p%%", "new notes", "%%pct" FROM test_invalid_identifiers WHERE id = %(p1)s
"""

INSERT_THIRD_PARTY_STAT: typing.Final[typing.LiteralString] = """-- name: InsertThirdPartyStat :exec
INSERT INTO "3rd_party_stats" (id, total) VALUES (%(p1)s, %(p2)s)
"""

GET_THIRD_PARTY_STAT: typing.Final[typing.LiteralString] = """-- name: GetThirdPartyStat :one
SELECT id, total FROM "3rd_party_stats" WHERE id = %(p1)s
"""


def insert_invalid_identifiers(conn: ConnectionLike, *, id_: int, column_3p_: str | None, new_notes: str) -> None:
    """Execute SQL query with `name: InsertInvalidIdentifiers :exec`.

    ```sql
    INSERT INTO test_invalid_identifiers (id, "3p%%", "new notes") VALUES (%(p1)s, %(p2)s, %(p3)s)
    ```

    Args:
        conn:
            Connection object of type `ConnectionLike` used to execute the query.
        id_: int.
        column_3p_: str | None.
        new_notes: str.
    """
    conn.execute(INSERT_INVALID_IDENTIFIERS, {"p1": id_, "p2": column_3p_, "p3": new_notes})


def get_invalid_identifiers(conn: ConnectionLike, *, id_: int) -> models.TestInvalidIdentifier | None:
    """Fetch one from the db using the SQL query with `name: GetInvalidIdentifiers :one`.

    ```sql
    SELECT id, "3p%%", "new notes", "%%pct" FROM test_invalid_identifiers WHERE id = %(p1)s
    ```

    Args:
        conn:
            Connection object of type `ConnectionLike` used to execute the query.
        id_: int.

    Returns:
        Result of type `models.TestInvalidIdentifier` fetched from the db. Will be `None` if not found.
    """
    row = conn.execute(GET_INVALID_IDENTIFIERS, {"p1": id_}).fetchone()
    if row is None:
        return None
    return models.TestInvalidIdentifier(id_=row[0], column_3p_=row[1], new_notes=row[2], column__pct=row[3])


def insert_third_party_stat(conn: ConnectionLike, *, id_: int, total: int) -> None:
    """Execute SQL query with `name: InsertThirdPartyStat :exec`.

    ```sql
    INSERT INTO "3rd_party_stats" (id, total) VALUES (%(p1)s, %(p2)s)
    ```

    Args:
        conn:
            Connection object of type `ConnectionLike` used to execute the query.
        id_: int.
        total: int.
    """
    conn.execute(INSERT_THIRD_PARTY_STAT, {"p1": id_, "p2": total})


def get_third_party_stat(conn: ConnectionLike, *, id_: int) -> models.Model3RdPartyStat | None:
    """Fetch one from the db using the SQL query with `name: GetThirdPartyStat :one`.

    ```sql
    SELECT id, total FROM "3rd_party_stats" WHERE id = %(p1)s
    ```

    Args:
        conn:
            Connection object of type `ConnectionLike` used to execute the query.
        id_: int.

    Returns:
        Result of type `models.Model3RdPartyStat` fetched from the db. Will be `None` if not found.
    """
    row = conn.execute(GET_THIRD_PARTY_STAT, {"p1": id_}).fetchone()
    if row is None:
        return None
    return models.Model3RdPartyStat(id_=row[0], total=row[1])
