# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.6.0
# source file: queries_converters.sql
"""Module containing queries from file queries_converters.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "QueryResults",
    "delete_converted",
    "find_converter_array_by_labels",
    "get_converted",
    "get_converter_array_label",
    "insert_converted",
    "insert_converter_array_row",
    "list_converted_by_tags",
)

import operator
import psycopg
import psycopg.rows
import psycopg.types.string
import test.converters
import typing

if typing.TYPE_CHECKING:
    from pathlib import PurePosixPath
    from test.converters import Preferences
    import collections.abc

    type QueryResultsArgsType = int | float | str | memoryview | collections.abc.Sequence[QueryResultsArgsType] | None

    type ConnectionLike = psycopg.Connection[psycopg.rows.TupleRow]

from test.driver_psycopg_sync.dataclass.functions import models


psycopg.adapters.register_loader("jsonb", psycopg.types.string.TextLoader)


INSERT_CONVERTED: typing.Final[typing.LiteralString] = """-- name: InsertConverted :exec
INSERT INTO test_converters (id, prefs, maybe_prefs, tags) VALUES (%(p1)s, %(p2)s, %(p3)s, %(p4)s)
"""

GET_CONVERTED: typing.Final[typing.LiteralString] = """-- name: GetConverted :one
SELECT id, prefs, maybe_prefs, tags FROM test_converters WHERE id = %(p1)s
"""

LIST_CONVERTED_BY_TAGS: typing.Final[typing.LiteralString] = """-- name: ListConvertedByTags :many
SELECT id FROM test_converters WHERE tags = %(p1)s
"""

DELETE_CONVERTED: typing.Final[typing.LiteralString] = """-- name: DeleteConverted :exec
DELETE FROM test_converters WHERE id = %(p1)s
"""

INSERT_CONVERTER_ARRAY_ROW: typing.Final[typing.LiteralString] = """-- name: InsertConverterArrayRow :exec
INSERT INTO test_converter_array (id, label) VALUES (%(p1)s, %(p2)s)
"""

GET_CONVERTER_ARRAY_LABEL: typing.Final[typing.LiteralString] = """-- name: GetConverterArrayLabel :one
SELECT label FROM test_converter_array WHERE id = %(p1)s
"""

FIND_CONVERTER_ARRAY_BY_LABELS: typing.Final[typing.LiteralString] = """-- name: FindConverterArrayByLabels :many
SELECT id FROM test_converter_array WHERE label = ANY(%(p1)s::converter_label[])
"""


class QueryResults[T]:
    """Helper class that allows both iteration and normal fetching of data from the db."""

    __slots__ = ("_conn", "_cursor", "_decode_hook", "_iterator", "_params", "_sql")

    def __init__(
        self,
        conn: ConnectionLike,
        sql: typing.LiteralString,
        decode_hook: collections.abc.Callable[[psycopg.rows.TupleRow], T],
        params: dict[str, QueryResultsArgsType] | None = None,
    ) -> None:
        """Initialize the QueryResults instance.

        Args:
            conn:
                The connection object of type `ConnectionLike` used to execute queries.
            sql:
                The SQL statement that will be executed when fetching/iterating.
            decode_hook:
                A callback that turns an `psycopg.rows.TupleRow` object into `T` that will be returned.
            params:
                Named arguments that should be sent when executing the sql query.
        """
        self._conn = conn
        self._sql: typing.LiteralString = sql
        self._decode_hook = decode_hook
        self._params = params
        self._cursor: psycopg.Cursor[psycopg.rows.TupleRow] | None = None
        self._iterator: collections.abc.Iterator[psycopg.rows.TupleRow] | None = None

    def __iter__(self) -> QueryResults[T]:
        """Initialize iteration support.

        Returns:
            Self as an iterator.
        """
        return self

    def __call__(
        self,
    ) -> collections.abc.Sequence[T]:
        """Allow calling the object to return all rows as a fully decoded sequence.

        Returns:
            A sequence of decoded objects of type `T`.
        """
        result = self._conn.execute(self._sql, self._params).fetchall()
        return [self._decode_hook(row) for row in result]

    def __next__(self) -> T:
        """Yield the next item in the query result using a psycopg cursor.

        Returns:
            The next decoded result of type `T`.

        Raises:
            StopIteration: When no more records are available.
        """
        if self._cursor is None or self._iterator is None:
            self._cursor = self._conn.execute(self._sql, self._params)
            self._iterator = self._cursor.__iter__()
        try:
            record = self._iterator.__next__()
        except StopIteration:
            self._cursor = None
            self._iterator = None
            raise
        return self._decode_hook(record)


def insert_converted(conn: ConnectionLike, *, id_: int, prefs: Preferences, maybe_prefs: Preferences | None, tags: frozenset[str]) -> None:
    """Execute SQL query with `name: InsertConverted :exec`.

    ```sql
    INSERT INTO test_converters (id, prefs, maybe_prefs, tags) VALUES (%(p1)s, %(p2)s, %(p3)s, %(p4)s)
    ```

    Args:
        conn:
            Connection object of type `ConnectionLike` used to execute the query.
        id_: int.
        prefs: Preferences.
        maybe_prefs: Preferences | None.
        tags: frozenset[str].
    """
    conn.execute(INSERT_CONVERTED, {"p1": id_, "p2": test.converters.encode_preferences(prefs), "p3": test.converters.encode_preferences(maybe_prefs) if maybe_prefs is not None else None, "p4": test.converters.encode_tags(tags)})


def get_converted(conn: ConnectionLike, *, id_: int) -> models.TestConverter | None:
    """Fetch one from the db using the SQL query with `name: GetConverted :one`.

    ```sql
    SELECT id, prefs, maybe_prefs, tags FROM test_converters WHERE id = %(p1)s
    ```

    Args:
        conn:
            Connection object of type `ConnectionLike` used to execute the query.
        id_: int.

    Returns:
        Result of type `models.TestConverter` fetched from the db. Will be `None` if not found.
    """
    row = conn.execute(GET_CONVERTED, {"p1": id_}).fetchone()
    if row is None:
        return None
    return models.TestConverter(id_=row[0], prefs=test.converters.decode_preferences(row[1]), maybe_prefs=test.converters.decode_preferences(row[2]) if row[2] is not None else None, tags=test.converters.decode_tags(row[3]))


def list_converted_by_tags(conn: ConnectionLike, *, tags: frozenset[str]) -> QueryResults[int]:
    """Fetch many from the db using the SQL query with `name: ListConvertedByTags :many`.

    ```sql
    SELECT id FROM test_converters WHERE tags = %(p1)s
    ```

    Args:
        conn:
            Connection object of type `ConnectionLike` used to execute the query.
        tags: frozenset[str].

    Returns:
        Helper class of type `QueryResults[int]` that allows both iteration and normal fetching of data from the db.
    """
    return QueryResults(conn, LIST_CONVERTED_BY_TAGS, operator.itemgetter(0), {"p1": test.converters.encode_tags(tags)})


def delete_converted(conn: ConnectionLike, *, id_: int) -> None:
    """Execute SQL query with `name: DeleteConverted :exec`.

    ```sql
    DELETE FROM test_converters WHERE id = %(p1)s
    ```

    Args:
        conn:
            Connection object of type `ConnectionLike` used to execute the query.
        id_: int.
    """
    conn.execute(DELETE_CONVERTED, {"p1": id_})


def insert_converter_array_row(conn: ConnectionLike, *, id_: int, label: PurePosixPath) -> None:
    """Execute SQL query with `name: InsertConverterArrayRow :exec`.

    ```sql
    INSERT INTO test_converter_array (id, label) VALUES (%(p1)s, %(p2)s)
    ```

    Args:
        conn:
            Connection object of type `ConnectionLike` used to execute the query.
        id_: int.
        label: PurePosixPath.
    """
    conn.execute(INSERT_CONVERTER_ARRAY_ROW, {"p1": id_, "p2": test.converters.encode_label(label)})


def get_converter_array_label(conn: ConnectionLike, *, id_: int) -> PurePosixPath | None:
    """Fetch one from the db using the SQL query with `name: GetConverterArrayLabel :one`.

    ```sql
    SELECT label FROM test_converter_array WHERE id = %(p1)s
    ```

    Args:
        conn:
            Connection object of type `ConnectionLike` used to execute the query.
        id_: int.

    Returns:
        Result of type `PurePosixPath` fetched from the db. Will be `None` if not found.
    """
    row = conn.execute(GET_CONVERTER_ARRAY_LABEL, {"p1": id_}).fetchone()
    if row is None:
        return None
    return test.converters.decode_label(row[0])


def find_converter_array_by_labels(conn: ConnectionLike, *, dollar_1: collections.abc.Sequence[PurePosixPath]) -> QueryResults[int]:
    """Fetch many from the db using the SQL query with `name: FindConverterArrayByLabels :many`.

    ```sql
    SELECT id FROM test_converter_array WHERE label = ANY(%(p1)s::converter_label[])
    ```

    Args:
        conn:
            Connection object of type `ConnectionLike` used to execute the query.
        dollar_1: collections.abc.Sequence[PurePosixPath].

    Returns:
        Helper class of type `QueryResults[int]` that allows both iteration and normal fetching of data from the db.
    """
    return QueryResults(conn, FIND_CONVERTER_ARRAY_BY_LABELS, operator.itemgetter(0), {"p1": [test.converters.encode_label(v) for v in dollar_1]})
