changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '* [#{{.Custom.PR}}](https://github.com/rayakame/sqlc-gen-better-python/pull/{{.Custom.PR}}) {{.Body}} ([{{.Custom.Author}}](https://github.com/{{.Custom.Author}}))'
custom:
  - key: PR
    type: int
    minInt: 1
  - key: Author
    label: GitHub Name
    type: string
    minLength: 3
kinds:
    - label: Added
      auto: minor
    - label: Changed
      auto: major
    - label: Deprecated
      auto: minor
    - label: Removed
      auto: major
    - label: Fixed
      auto: patch
    - label: Security
      auto: patch
    - label: Dependencys
      auto: patch
newlines:
    afterChangelogHeader: 1
    beforeChangelogVersion: 1
    endOfVersion: 1
envPrefix: CHANGIE_
