# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.8.0
# source file: queries_field_namings.sql
"""Module containing queries from file queries_field_namings.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "GetJoinedFieldNamingsRow",
    "get_field_naming",
    "get_joined_field_namings",
    "set_field_naming_outputs",
)

import msgspec
import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import pymysql

from test.driver_pymysql.msgspec.functions import models


class GetJoinedFieldNamingsRow(msgspec.Struct):
    """Model representing GetJoinedFieldNamingsRow.

    Attributes:
    outputs -- str
    outputs_2 -- str
    """

    outputs: str
    outputs_2: str


GET_FIELD_NAMING: typing.Final[str] = """-- name: GetFieldNaming :one
SELECT id, outputs
FROM test_field_namings
WHERE id = %s LIMIT 1
"""

GET_JOINED_FIELD_NAMINGS: typing.Final[str] = """-- name: GetJoinedFieldNamings :one
SELECT a.outputs, b.outputs
FROM test_field_namings a
JOIN test_field_namings b ON a.id = b.id
WHERE a.id = %s LIMIT 1
"""

SET_FIELD_NAMING_OUTPUTS: typing.Final[str] = """-- name: SetFieldNamingOutputs :exec
UPDATE test_field_namings
SET outputs = %s
WHERE id = %s
"""


def get_field_naming(conn: pymysql.Connection, *, id_: int) -> models.TestFieldNaming | None:
    """Fetch one from the db using the SQL query with `name: GetFieldNaming :one`.

    ```sql
    SELECT id, outputs
    FROM test_field_namings
    WHERE id = %s LIMIT 1
    ```

    Arguments:
    conn -- Connection object of type `pymysql.Connection` used to execute the query.
    id_ -- int.

    Returns:
    models.TestFieldNaming -- Result fetched from the db. Will be `None` if not found.
    """
    with conn.cursor() as cur:
        cur.execute(GET_FIELD_NAMING, (id_,))
        row = cur.fetchone()
    if row is None:
        return None
    return models.TestFieldNaming(id_=row[0], outputs=row[1])


def get_joined_field_namings(conn: pymysql.Connection, *, id_: int) -> GetJoinedFieldNamingsRow | None:
    """Fetch one from the db using the SQL query with `name: GetJoinedFieldNamings :one`.

    ```sql
    SELECT a.outputs, b.outputs
    FROM test_field_namings a
    JOIN test_field_namings b ON a.id = b.id
    WHERE a.id = %s LIMIT 1
    ```

    Arguments:
    conn -- Connection object of type `pymysql.Connection` used to execute the query.
    id_ -- int.

    Returns:
    GetJoinedFieldNamingsRow -- Result fetched from the db. Will be `None` if not found.
    """
    with conn.cursor() as cur:
        cur.execute(GET_JOINED_FIELD_NAMINGS, (id_,))
        row = cur.fetchone()
    if row is None:
        return None
    return GetJoinedFieldNamingsRow(outputs=row[0], outputs_2=row[1])


def set_field_naming_outputs(conn: pymysql.Connection, *, outputs: str, id_: int) -> None:
    """Execute SQL query with `name: SetFieldNamingOutputs :exec`.

    ```sql
    UPDATE test_field_namings
    SET outputs = %s
    WHERE id = %s
    ```

    Arguments:
    conn -- Connection object of type `pymysql.Connection` used to execute the query.
    outputs -- str.
    id_ -- int.
    """
    with conn.cursor() as cur:
        cur.execute(SET_FIELD_NAMING_OUTPUTS, (outputs, id_))
