# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.6.0
# source file: queries_invalid_identifiers.sql
"""Module containing queries from file queries_invalid_identifiers.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = ("QueriesInvalidIdentifiers",)

import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import psycopg
    import psycopg.rows

    type ConnectionLike = psycopg.AsyncConnection[psycopg.rows.TupleRow]

from test.driver_psycopg_async.pydantic.classes import models


INSERT_INVALID_IDENTIFIERS: typing.Final[typing.LiteralString] = """-- name: InsertInvalidIdentifiers :exec
INSERT INTO test_invalid_identifiers (id, "3p%%", "new notes") VALUES (%(p1)s, %(p2)s, %(p3)s)
"""

GET_INVALID_IDENTIFIERS: typing.Final[typing.LiteralString] = """-- name: GetInvalidIdentifiers :one
SELECT id, "3p%%", "new notes", "%%pct" FROM test_invalid_identifiers WHERE id = %(p1)s
"""

INSERT_THIRD_PARTY_STAT: typing.Final[typing.LiteralString] = """-- name: InsertThirdPartyStat :exec
INSERT INTO "3rd_party_stats" (id, total) VALUES (%(p1)s, %(p2)s)
"""

GET_THIRD_PARTY_STAT: typing.Final[typing.LiteralString] = """-- name: GetThirdPartyStat :one
SELECT id, total FROM "3rd_party_stats" WHERE id = %(p1)s
"""


class QueriesInvalidIdentifiers:
    """Queries from file queries_invalid_identifiers.sql."""

    __slots__ = ("_conn",)

    def __init__(self, conn: ConnectionLike) -> None:
        """Initialize the instance using the connection.

        Args:
            conn:
                Connection object of type `ConnectionLike` used to execute the query.
        """
        self._conn = conn

    @property
    def conn(self) -> ConnectionLike:
        """Connection object used to make queries.

        Returns:
            Connection object of type `ConnectionLike` used to make queries.
        """
        return self._conn

    async def insert_invalid_identifiers(self, *, id_: int, column_3p_: str | None, new_notes: str) -> None:
        """Execute SQL query with `name: InsertInvalidIdentifiers :exec`.

        ```sql
        INSERT INTO test_invalid_identifiers (id, "3p%%", "new notes") VALUES (%(p1)s, %(p2)s, %(p3)s)
        ```

        Args:
            id_: int.
            column_3p_: str | None.
            new_notes: str.
        """
        await self._conn.execute(INSERT_INVALID_IDENTIFIERS, {"p1": id_, "p2": column_3p_, "p3": new_notes})

    async def get_invalid_identifiers(self, *, id_: int) -> models.TestInvalidIdentifier | None:
        """Fetch one from the db using the SQL query with `name: GetInvalidIdentifiers :one`.

        ```sql
        SELECT id, "3p%%", "new notes", "%%pct" FROM test_invalid_identifiers WHERE id = %(p1)s
        ```

        Args:
            id_: int.

        Returns:
            Result of type `models.TestInvalidIdentifier` fetched from the db. Will be `None` if not found.
        """
        row = await (await self._conn.execute(GET_INVALID_IDENTIFIERS, {"p1": id_})).fetchone()
        if row is None:
            return None
        return models.TestInvalidIdentifier(id_=row[0], column_3p_=row[1], new_notes=row[2], column__pct=row[3])

    async def insert_third_party_stat(self, *, id_: int, total: int) -> None:
        """Execute SQL query with `name: InsertThirdPartyStat :exec`.

        ```sql
        INSERT INTO "3rd_party_stats" (id, total) VALUES (%(p1)s, %(p2)s)
        ```

        Args:
            id_: int.
            total: int.
        """
        await self._conn.execute(INSERT_THIRD_PARTY_STAT, {"p1": id_, "p2": total})

    async def get_third_party_stat(self, *, id_: int) -> models.Model3RdPartyStat | None:
        """Fetch one from the db using the SQL query with `name: GetThirdPartyStat :one`.

        ```sql
        SELECT id, total FROM "3rd_party_stats" WHERE id = %(p1)s
        ```

        Args:
            id_: int.

        Returns:
            Result of type `models.Model3RdPartyStat` fetched from the db. Will be `None` if not found.
        """
        row = await (await self._conn.execute(GET_THIRD_PARTY_STAT, {"p1": id_})).fetchone()
        if row is None:
            return None
        return models.Model3RdPartyStat(id_=row[0], total=row[1])
