# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.6.0
# source file: queries_copy_override.sql
"""Module containing queries from file queries_copy_override.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "CopyOverrideRowsParams",
    "QueriesCopyOverride",
)

import decimal
import pydantic
import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import psycopg
    import psycopg.rows

    type ConnectionLike = psycopg.AsyncConnection[psycopg.rows.TupleRow]


class CopyOverrideRowsParams(pydantic.BaseModel):
    """Model representing CopyOverrideRowsParams.

    Attributes:
        id_: int
        amount: float
        co_l: str
    """

    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    amount: float
    co_l: str


COPY_OVERRIDE_ROWS: typing.Final[typing.LiteralString] = """-- name: CopyOverrideRows :copyfrom
INSERT INTO test_copy_override (id, amount, "co""l") VALUES ($1, $2, $3)
"""

COUNT_COPY_OVERRIDE_ROWS: typing.Final[typing.LiteralString] = """-- name: CountCopyOverrideRows :one
SELECT count(*) FROM test_copy_override
"""

DELETE_COPY_OVERRIDE_ROWS: typing.Final[typing.LiteralString] = """-- name: DeleteCopyOverrideRows :exec
DELETE FROM test_copy_override
"""


class QueriesCopyOverride:
    """Queries from file queries_copy_override.sql."""

    __slots__ = ("_conn",)

    def __init__(self, conn: ConnectionLike) -> None:
        """Initialize the instance using the connection.

        Args:
            conn:
                Connection object of type `ConnectionLike` used to execute the query.
        """
        self._conn = conn

    @property
    def conn(self) -> ConnectionLike:
        """Connection object used to make queries.

        Returns:
            Connection object of type `ConnectionLike` used to make queries.
        """
        return self._conn

    async def copy_override_rows(self, *, params: collections.abc.Sequence[CopyOverrideRowsParams]) -> int:
        """Execute COPY FROM query to insert rows into a table with `name: CopyOverrideRows :copyfrom` and return the number of affected rows.

        Args:
            params: collections.abc.Sequence[CopyOverrideRowsParams].
                A list of params for rows that should be inserted.

        Returns:
            The number (`int`) of affected rows.
        """
        async with self._conn.cursor() as cur:
            async with cur.copy('COPY "test_copy_override" ("id", "amount", "co""l") FROM STDIN') as copy:
                for param in params:
                    await copy.write_row((param.id_, decimal.Decimal(param.amount), param.co_l))
            return cur.rowcount

    async def count_copy_override_rows(self) -> int | None:
        """Fetch one from the db using the SQL query with `name: CountCopyOverrideRows :one`.

        ```sql
        SELECT count(*) FROM test_copy_override
        ```

        Returns:
            Result of type `int` fetched from the db. Will be `None` if not found.
        """
        row = await (await self._conn.execute(COUNT_COPY_OVERRIDE_ROWS)).fetchone()
        if row is None:
            return None
        return row[0]

    async def delete_copy_override_rows(self) -> None:
        """Execute SQL query with `name: DeleteCopyOverrideRows :exec`.

        ```sql
        DELETE FROM test_copy_override
        ```

        """
        await self._conn.execute(DELETE_COPY_OVERRIDE_ROWS)
