package codegen

import (
	"github.com/rayakame/sqlc-gen-better-python/internal/core"
	"os"
	"strings"
)

type IndentStringBuilder struct {
	strings.Builder

	indentChar          string
	charsPerIndentLevel int
}

func NewIndentStringBuilder(indentChar string, charsPerIndentLevel int) *IndentStringBuilder {
	return &IndentStringBuilder{
		indentChar:          indentChar,
		charsPerIndentLevel: charsPerIndentLevel,
	}
}

func (b *IndentStringBuilder) WriteIndentedString(level int, s string) int {
	count, _ := b.WriteString(strings.Repeat(b.indentChar, level*b.charsPerIndentLevel) + s)
	return count
}

func (b *IndentStringBuilder) WriteSqlcHeader() {
	sqlcVersion := os.Getenv("SQLC_VERSION")

	b.WriteString("# Code generated by sqlc. DO NOT EDIT.\n")
	b.WriteString("# versions:\n")
	b.WriteString("#   sqlc " + sqlcVersion + "\n")
	b.WriteString("#   sqlc-gen-better-python " + core.PluginVersion + "\n")
}

func (b *IndentStringBuilder) WriteLine(txt string) {
	b.WriteString(txt)
	b.WriteString("\n")
}
