package builders

import (
	"os"
	"strings"

	"github.com/rayakame/sqlc-gen-better-python/internal/config"
	"github.com/rayakame/sqlc-gen-better-python/internal/log"
)

type IndentStringBuilder struct {
	builder strings.Builder

	indentChar          string
	charsPerIndentLevel int

	docstringOmitSQL    bool
	docstringConvention config.DocstringConvention
	docstringDriver     config.SQLDriver
}

func NewIndentStringBuilder(
	indentChar string,
	charsPerIndentLevel int,
	docstringConvention config.DocstringConvention,
	docstringOmitSQL bool,
	docstringDriver config.SQLDriver,
) *IndentStringBuilder {
	return &IndentStringBuilder{
		builder:             strings.Builder{},
		indentChar:          indentChar,
		charsPerIndentLevel: charsPerIndentLevel,
		docstringConvention: docstringConvention,
		docstringDriver:     docstringDriver,
		docstringOmitSQL:    docstringOmitSQL,
	}
}

func (b *IndentStringBuilder) WriteIndentedString(level int, txt string) {
	b.WriteString(strings.Repeat(b.indentChar, level*b.charsPerIndentLevel) + txt)
}

func (b *IndentStringBuilder) WriteSqlcHeader() {
	sqlcVersion := os.Getenv("SQLC_VERSION")

	b.WriteString("# Code generated by sqlc. DO NOT EDIT.\n")
	b.WriteString("# versions:\n")
	b.WriteString("#   sqlc " + sqlcVersion + "\n")
	b.WriteString("#   sqlc-gen-better-python " + config.PluginVersion + "\n")
}

func (b *IndentStringBuilder) WriteString(txt string) {
	_, err := b.builder.WriteString(txt)
	if err != nil {
		log.L().LogErr("Error while trying to write string", err)
	}
}

func (b *IndentStringBuilder) WriteLine(txt string) {
	b.WriteString(txt)
	b.WriteString("\n")
}

func (b *IndentStringBuilder) WriteIndentedLine(level int, txt string) {
	b.WriteIndentedString(level, txt)
	b.WriteString("\n")
}

func (b *IndentStringBuilder) WriteImportAnnotations() {
	b.WriteLine("from __future__ import annotations")
	b.WriteString("\n")
}

func (b *IndentStringBuilder) NewLine() {
	b.WriteString("\n")
}

func (b *IndentStringBuilder) NNewLine(n int) {
	for range n {
		b.WriteString("\n")
	}
}

func (b *IndentStringBuilder) Bytes() []byte {
	return []byte(b.builder.String())
}
