# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.6.0
# source file: queries_case.sql
"""Module containing queries from file queries_case.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "GetCaseRowRow",
    "QueriesCase",
)

import datetime
import decimal
import msgspec
import sqlite3
import typing

if typing.TYPE_CHECKING:
    import collections.abc


def _adapt_decimal(val: decimal.Decimal) -> str:
    return str(val)


def _convert_decimal(val: bytes) -> decimal.Decimal:
    return decimal.Decimal(val.decode())


def _adapt_datetime(val: datetime.datetime) -> str:
    return val.isoformat()


def _convert_datetime(val: bytes) -> datetime.datetime:
    return datetime.datetime.fromisoformat(val.decode())


sqlite3.register_adapter(decimal.Decimal, _adapt_decimal)
sqlite3.register_adapter(datetime.datetime, _adapt_datetime)

sqlite3.register_converter("decimal", _convert_decimal)
sqlite3.register_converter("datetime", _convert_datetime)
sqlite3.register_converter("timestamp", _convert_datetime)


class GetCaseRowRow(msgspec.Struct):
    """Model representing GetCaseRowRow.

    Attributes:
    upper_dt -- datetime.datetime
    prec_dec -- decimal.Decimal
    """

    upper_dt: datetime.datetime
    prec_dec: decimal.Decimal


INSERT_CASE_ROW: typing.Final[str] = """-- name: InsertCaseRow :exec
INSERT INTO test_case_sensitivity (id, upper_dt, prec_dec) VALUES (?, ?, ?)
"""

GET_CASE_ROW: typing.Final[str] = """-- name: GetCaseRow :one
SELECT upper_dt, prec_dec FROM test_case_sensitivity WHERE id = ?
"""

INSERT_RESERVED_ARG: typing.Final[str] = """-- name: InsertReservedArg :exec
INSERT INTO test_reserved_args (id, conn) VALUES (?, ?)
"""

GET_RESERVED_ARG: typing.Final[str] = """-- name: GetReservedArg :one
SELECT id FROM test_reserved_args WHERE conn = ?
"""


class QueriesCase:
    """Queries from file queries_case.sql."""

    __slots__ = ("_conn",)

    def __init__(self, conn: sqlite3.Connection) -> None:
        """Initialize the instance using the connection.

        Arguments:
        conn -- Connection object of type `sqlite3.Connection` used to execute queries.
        """
        self._conn = conn

    @property
    def conn(self) -> sqlite3.Connection:
        """Connection object used to make queries.

        Returns:
        sqlite3.Connection -- Connection object used to make queries.
        """
        return self._conn

    def insert_case_row(self, *, id_: int, upper_dt: datetime.datetime, prec_dec: decimal.Decimal) -> None:
        """Execute SQL query with `name: InsertCaseRow :exec`.

        ```sql
        INSERT INTO test_case_sensitivity (id, upper_dt, prec_dec) VALUES (?, ?, ?)
        ```

        Arguments:
        id_ -- int.
        upper_dt -- datetime.datetime.
        prec_dec -- decimal.Decimal.
        """
        self._conn.execute(INSERT_CASE_ROW, (id_, upper_dt, prec_dec))

    def get_case_row(self, *, id_: int) -> GetCaseRowRow | None:
        """Fetch one from the db using the SQL query with `name: GetCaseRow :one`.

        ```sql
        SELECT upper_dt, prec_dec FROM test_case_sensitivity WHERE id = ?
        ```

        Arguments:
        id_ -- int.

        Returns:
        GetCaseRowRow -- Result fetched from the db. Will be `None` if not found.
        """
        row = self._conn.execute(GET_CASE_ROW, (id_,)).fetchone()
        if row is None:
            return None
        return GetCaseRowRow(upper_dt=row[0], prec_dec=row[1])

    def insert_reserved_arg(self, *, id_: int, conn: str) -> None:
        """Execute SQL query with `name: InsertReservedArg :exec`.

        ```sql
        INSERT INTO test_reserved_args (id, conn) VALUES (?, ?)
        ```

        Arguments:
        id_ -- int.
        conn -- str.
        """
        self._conn.execute(INSERT_RESERVED_ARG, (id_, conn))

    def get_reserved_arg(self, *, conn: str) -> int | None:
        """Fetch one from the db using the SQL query with `name: GetReservedArg :one`.

        ```sql
        SELECT id FROM test_reserved_args WHERE conn = ?
        ```

        Arguments:
        conn -- str.

        Returns:
        int -- Result fetched from the db. Will be `None` if not found.
        """
        row = self._conn.execute(GET_RESERVED_ARG, (conn,)).fetchone()
        if row is None:
            return None
        return row[0]
