# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
#   sqlc-gen-better-python v0.5.0
# source file: queries_unknown_override.sql
"""Module containing queries from file queries_unknown_override.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = ("QueriesUnknownOverride",)

import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import sqlite3


INSERT_UNKNOWN_OVERRIDE: typing.Final[str] = """-- name: InsertUnknownOverride :exec
INSERT INTO test_unknown_override (id, happened_at) VALUES (?, ?)
"""

GET_UNKNOWN_OVERRIDE: typing.Final[str] = """-- name: GetUnknownOverride :one
SELECT happened_at FROM test_unknown_override WHERE id = ?
"""


class QueriesUnknownOverride:
    """Queries from file queries_unknown_override.sql."""

    __slots__ = ("_conn",)

    def __init__(self, conn: sqlite3.Connection) -> None:
        """Initialize the instance using the connection.

        Arguments:
        conn -- Connection object of type `sqlite3.Connection` used to execute queries.
        """
        self._conn = conn

    @property
    def conn(self) -> sqlite3.Connection:
        """Connection object used to make queries.

        Returns:
        sqlite3.Connection -- Connection object used to make queries.
        """
        return self._conn

    def insert_unknown_override(self, *, id_: int, happened_at: str | None) -> None:
        """Execute SQL query with `name: InsertUnknownOverride :exec`.

        ```sql
        INSERT INTO test_unknown_override (id, happened_at) VALUES (?, ?)
        ```

        Arguments:
        id_ -- int.
        happened_at -- str | None.
        """
        self._conn.execute(INSERT_UNKNOWN_OVERRIDE, (id_, happened_at))

    def get_unknown_override(self, *, id_: int) -> str | None:
        """Fetch one from the db using the SQL query with `name: GetUnknownOverride :one`.

        ```sql
        SELECT happened_at FROM test_unknown_override WHERE id = ?
        ```

        Arguments:
        id_ -- int.

        Returns:
        str -- Result fetched from the db. Will be `None` if not found.
        """
        row = self._conn.execute(GET_UNKNOWN_OVERRIDE, (id_,)).fetchone()
        if row is None:
            return None
        return str(row[0]) if row[0] is not None else None
