# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.5.1
# source file: queries_copy_override.sql
"""Module containing queries from file queries_copy_override.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "CopyOverrideRowsParams",
    "QueriesCopyOverride",
)

import decimal
import msgspec
import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import collections.abc

    type ConnectionLike = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]


class CopyOverrideRowsParams(msgspec.Struct):
    """Model representing CopyOverrideRowsParams.

    Attributes:
    id_ -- int
    amount -- float
    co_l -- str
    """

    id_: int
    amount: float
    co_l: str


COPY_OVERRIDE_ROWS: typing.Final[str] = """-- name: CopyOverrideRows :copyfrom
INSERT INTO test_copy_override (id, amount, "co""l") VALUES ($1, $2, $3)
"""

COUNT_COPY_OVERRIDE_ROWS: typing.Final[str] = """-- name: CountCopyOverrideRows :one
SELECT count(*) FROM test_copy_override
"""

DELETE_COPY_OVERRIDE_ROWS: typing.Final[str] = """-- name: DeleteCopyOverrideRows :exec
DELETE FROM test_copy_override
"""


class QueriesCopyOverride:
    """Queries from file queries_copy_override.sql."""

    __slots__ = ("_conn",)

    def __init__(self, conn: ConnectionLike) -> None:
        """Initialize the instance using the connection.

        Arguments:
        conn -- Connection object of type `ConnectionLike` used to execute queries.
        """
        self._conn = conn

    @property
    def conn(self) -> ConnectionLike:
        """Connection object used to make queries.

        Returns:
        ConnectionLike -- Connection object used to make queries.
        """
        return self._conn

    async def copy_override_rows(self, *, params: collections.abc.Sequence[CopyOverrideRowsParams]) -> int:
        """Execute COPY FROM query to insert rows into a table with `name: CopyOverrideRows :copyfrom` and return the number of affected rows.

        Arguments:
        params -- collections.abc.Sequence[CopyOverrideRowsParams]. A list of params for rows that should be inserted.

        Returns:
        int -- The number of affected rows.
        """
        records = [(param.id_, decimal.Decimal(param.amount), param.co_l) for param in params]
        r = await self._conn.copy_records_to_table("test_copy_override", columns=["id", "amount", 'co"l'], records=records)
        return int(n) if (p := r.split()) and (n := p[-1]).isdigit() else 0

    async def count_copy_override_rows(self) -> int | None:
        """Fetch one from the db using the SQL query with `name: CountCopyOverrideRows :one`.

        ```sql
        SELECT count(*) FROM test_copy_override
        ```

        Returns:
        int -- Result fetched from the db. Will be `None` if not found.
        """
        row = await self._conn.fetchrow(COUNT_COPY_OVERRIDE_ROWS)
        if row is None:
            return None
        return row[0]

    async def delete_copy_override_rows(self) -> None:
        """Execute SQL query with `name: DeleteCopyOverrideRows :exec`.

        ```sql
        DELETE FROM test_copy_override
        ```

        """
        await self._conn.execute(DELETE_COPY_OVERRIDE_ROWS)
