# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.8.0
# source file: queries_converters.sql
"""Module containing queries from file queries_converters.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "QueryResults",
    "delete_converted",
    "get_converted",
    "insert_converted",
    "list_converted_by_tags",
)

import operator
import test.converters
import typing

if typing.TYPE_CHECKING:
    from test.converters import Preferences
    import collections.abc
    import pymysql
    import pymysql.cursors

    type QueryResultsArgsType = int | float | str | memoryview | bytes | collections.abc.Sequence[QueryResultsArgsType] | None

from test.driver_pymysql.dataclass.functions import models


INSERT_CONVERTED: typing.Final[str] = """-- name: InsertConverted :exec
INSERT INTO test_converters (id, prefs, maybe_prefs, tags) VALUES (%s, %s, %s, %s)
"""

GET_CONVERTED: typing.Final[str] = """-- name: GetConverted :one
SELECT id, prefs, maybe_prefs, tags FROM test_converters WHERE id = %s
"""

LIST_CONVERTED_BY_TAGS: typing.Final[str] = """-- name: ListConvertedByTags :many
SELECT id FROM test_converters WHERE tags = %s
"""

DELETE_CONVERTED: typing.Final[str] = """-- name: DeleteConverted :exec
DELETE FROM test_converters WHERE id = %s
"""


class QueryResults[T]:
    """Helper class that allows both iteration and normal fetching of data from the db."""

    __slots__ = ("_args", "_conn", "_cursor", "_decode_hook", "_sql")

    def __init__(
        self,
        conn: pymysql.Connection,
        sql: str,
        decode_hook: collections.abc.Callable[[tuple[typing.Any, ...]], T],
        *args: QueryResultsArgsType,
    ) -> None:
        """Initialize the QueryResults instance.

        Args:
            conn:
                The connection object of type `pymysql.Connection` used to execute queries.
            sql:
                The SQL statement that will be executed when fetching/iterating.
            decode_hook:
                A callback that turns an `tuple[typing.Any, ...]` object into `T` that will be returned.
            *args:
                Arguments that should be sent when executing the sql query.
        """
        self._conn = conn
        self._sql = sql
        self._decode_hook = decode_hook
        self._args = args
        self._cursor: pymysql.cursors.Cursor | None = None

    def __iter__(self) -> QueryResults[T]:
        """Initialize iteration support.

        Returns:
            Self as an iterator.
        """
        return self

    def __call__(
        self,
    ) -> collections.abc.Sequence[T]:
        """Allow calling the object to return all rows as a fully decoded sequence.

        Returns:
            A sequence of decoded objects of type `T`.
        """
        cur = self._conn.cursor()
        cur.execute(self._sql, self._args)
        result = cur.fetchall()
        cur.close()
        return [self._decode_hook(row) for row in result]

    def __next__(self) -> T:
        """Yield the next item in the query result using a pymysql cursor.

        Returns:
            The next decoded result of type `T`.

        Raises:
            StopIteration: When no more records are available.
        """
        if self._cursor is None:
            self._cursor = self._conn.cursor()
            self._cursor.execute(self._sql, self._args)
        record = self._cursor.fetchone()
        if record is None:
            self._cursor = None
            raise StopIteration
        return self._decode_hook(record)


def insert_converted(conn: pymysql.Connection, *, id_: int, prefs: Preferences, maybe_prefs: Preferences | None, tags: frozenset[str]) -> None:
    """Execute SQL query with `name: InsertConverted :exec`.

    ```sql
    INSERT INTO test_converters (id, prefs, maybe_prefs, tags) VALUES (%s, %s, %s, %s)
    ```

    Args:
        conn:
            Connection object of type `pymysql.Connection` used to execute the query.
        id_: int.
        prefs: Preferences.
        maybe_prefs: Preferences | None.
        tags: frozenset[str].
    """
    with conn.cursor() as cur:
        cur.execute(INSERT_CONVERTED, (id_, test.converters.encode_preferences(prefs), test.converters.encode_preferences(maybe_prefs) if maybe_prefs is not None else None, test.converters.encode_tags(tags)))


def get_converted(conn: pymysql.Connection, *, id_: int) -> models.TestConverter | None:
    """Fetch one from the db using the SQL query with `name: GetConverted :one`.

    ```sql
    SELECT id, prefs, maybe_prefs, tags FROM test_converters WHERE id = %s
    ```

    Args:
        conn:
            Connection object of type `pymysql.Connection` used to execute the query.
        id_: int.

    Returns:
        Result of type `models.TestConverter` fetched from the db. Will be `None` if not found.
    """
    with conn.cursor() as cur:
        cur.execute(GET_CONVERTED, (id_,))
        row = cur.fetchone()
    if row is None:
        return None
    return models.TestConverter(id_=row[0], prefs=test.converters.decode_preferences(row[1]), maybe_prefs=test.converters.decode_preferences(row[2]) if row[2] is not None else None, tags=test.converters.decode_tags(row[3]))


def list_converted_by_tags(conn: pymysql.Connection, *, tags: frozenset[str]) -> QueryResults[int]:
    """Fetch many from the db using the SQL query with `name: ListConvertedByTags :many`.

    ```sql
    SELECT id FROM test_converters WHERE tags = %s
    ```

    Args:
        conn:
            Connection object of type `pymysql.Connection` used to execute the query.
        tags: frozenset[str].

    Returns:
        Helper class of type `QueryResults[int]` that allows both iteration and normal fetching of data from the db.
    """
    return QueryResults(conn, LIST_CONVERTED_BY_TAGS, operator.itemgetter(0), test.converters.encode_tags(tags))


def delete_converted(conn: pymysql.Connection, *, id_: int) -> None:
    """Execute SQL query with `name: DeleteConverted :exec`.

    ```sql
    DELETE FROM test_converters WHERE id = %s
    ```

    Args:
        conn:
            Connection object of type `pymysql.Connection` used to execute the query.
        id_: int.
    """
    with conn.cursor() as cur:
        cur.execute(DELETE_CONVERTED, (id_,))
