# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.8.0
# source file: queries_enum_override.sql
"""Module containing queries from file queries_enum_override.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "QueriesEnumOverride",
    "QueryResults",
)

import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import pymysql
    import pymysql.cursors

    type QueryResultsArgsType = int | float | str | memoryview | bytes | collections.abc.Sequence[QueryResultsArgsType] | None

from test.driver_pymysql.pydantic.classes import enums
from test.driver_pymysql.pydantic.classes import models


INSERT_ENUM_OVERRIDE: typing.Final[str] = """-- name: InsertEnumOverride :exec
INSERT INTO test_enum_override (id, mood_test) VALUES (%s, %s)
"""

GET_ENUM_OVERRIDE_MOOD: typing.Final[str] = """-- name: GetEnumOverrideMood :one
SELECT mood_test FROM test_enum_override WHERE id = %s
"""

LIST_ENUM_OVERRIDE_BY_IDS: typing.Final[str] = """-- name: ListEnumOverrideByIds :many
SELECT id, mood_test FROM test_enum_override WHERE id IN (/*SLICE:ids*/%s) ORDER BY id
"""

COUNT_ENUM_OVERRIDE_BY_MOODS: typing.Final[str] = """-- name: CountEnumOverrideByMoods :one
SELECT count(*) FROM test_enum_override WHERE mood_test IN (/*SLICE:moods*/%s)
"""


class QueryResults[T]:
    """Helper class that allows both iteration and normal fetching of data from the db."""

    __slots__ = ("_args", "_conn", "_cursor", "_decode_hook", "_sql")

    def __init__(
        self,
        conn: pymysql.Connection,
        sql: str,
        decode_hook: collections.abc.Callable[[tuple[typing.Any, ...]], T],
        *args: QueryResultsArgsType,
    ) -> None:
        """Initialize the QueryResults instance.

        Args:
            conn:
                The connection object of type `pymysql.Connection` used to execute queries.
            sql:
                The SQL statement that will be executed when fetching/iterating.
            decode_hook:
                A callback that turns an `tuple[typing.Any, ...]` object into `T` that will be returned.
            *args:
                Arguments that should be sent when executing the sql query.
        """
        self._conn = conn
        self._sql = sql
        self._decode_hook = decode_hook
        self._args = args
        self._cursor: pymysql.cursors.Cursor | None = None

    def __iter__(self) -> QueryResults[T]:
        """Initialize iteration support.

        Returns:
            Self as an iterator.
        """
        return self

    def __call__(
        self,
    ) -> collections.abc.Sequence[T]:
        """Allow calling the object to return all rows as a fully decoded sequence.

        Returns:
            A sequence of decoded objects of type `T`.
        """
        cur = self._conn.cursor()
        cur.execute(self._sql, self._args)
        result = cur.fetchall()
        cur.close()
        return [self._decode_hook(row) for row in result]

    def __next__(self) -> T:
        """Yield the next item in the query result using a pymysql cursor.

        Returns:
            The next decoded result of type `T`.

        Raises:
            StopIteration: When no more records are available.
        """
        if self._cursor is None:
            self._cursor = self._conn.cursor()
            self._cursor.execute(self._sql, self._args)
        record = self._cursor.fetchone()
        if record is None:
            self._cursor = None
            raise StopIteration
        return self._decode_hook(record)


class QueriesEnumOverride:
    """Queries from file queries_enum_override.sql."""

    __slots__ = ("_conn",)

    def __init__(self, conn: pymysql.Connection) -> None:
        """Initialize the instance using the connection.

        Args:
            conn:
                Connection object of type `pymysql.Connection` used to execute the query.
        """
        self._conn = conn

    @property
    def conn(self) -> pymysql.Connection:
        """Connection object used to make queries.

        Returns:
            Connection object of type `pymysql.Connection` used to make queries.
        """
        return self._conn

    def insert_enum_override(self, *, id_: int, mood_test: str) -> None:
        """Execute SQL query with `name: InsertEnumOverride :exec`.

        ```sql
        INSERT INTO test_enum_override (id, mood_test) VALUES (%s, %s)
        ```

        Args:
            id_: int.
            mood_test: str.
        """
        with self._conn.cursor() as cur:
            cur.execute(INSERT_ENUM_OVERRIDE, (id_, enums.TestEnumOverrideMoodTest(mood_test)))

    def get_enum_override_mood(self, *, id_: int) -> str | None:
        """Fetch one from the db using the SQL query with `name: GetEnumOverrideMood :one`.

        ```sql
        SELECT mood_test FROM test_enum_override WHERE id = %s
        ```

        Args:
            id_: int.

        Returns:
            Result of type `str` fetched from the db. Will be `None` if not found.
        """
        with self._conn.cursor() as cur:
            cur.execute(GET_ENUM_OVERRIDE_MOOD, (id_,))
            row = cur.fetchone()
        if row is None:
            return None
        return str(row[0])

    def list_enum_override_by_ids(self, *, ids: collections.abc.Sequence[int]) -> QueryResults[models.TestEnumOverride]:
        """Fetch many from the db using the SQL query with `name: ListEnumOverrideByIds :many`.

        ```sql
        SELECT id, mood_test FROM test_enum_override WHERE id IN (/*SLICE:ids*/%s) ORDER BY id
        ```

        Args:
            ids: collections.abc.Sequence[int].

        Returns:
            Helper class of type `QueryResults[models.TestEnumOverride]` that allows both iteration and normal fetching of data from the db.
        """

        def _decode_hook(row: tuple[typing.Any, ...]) -> models.TestEnumOverride:
            return models.TestEnumOverride(id_=row[0], mood_test=str(row[1]))

        sql = LIST_ENUM_OVERRIDE_BY_IDS.replace("/*SLICE:ids*/%s", ",".join(("%s",) * len(ids)) or "NULL", 1)
        return QueryResults(self._conn, sql, _decode_hook, *ids)

    def count_enum_override_by_moods(self, *, moods: collections.abc.Sequence[str]) -> int | None:
        """Fetch one from the db using the SQL query with `name: CountEnumOverrideByMoods :one`.

        ```sql
        SELECT count(*) FROM test_enum_override WHERE mood_test IN (/*SLICE:moods*/%s)
        ```

        Args:
            moods: collections.abc.Sequence[str].

        Returns:
            Result of type `int` fetched from the db. Will be `None` if not found.
        """
        sql = COUNT_ENUM_OVERRIDE_BY_MOODS.replace("/*SLICE:moods*/%s", ",".join(("%s",) * len(moods)) or "NULL", 1)
        with self._conn.cursor() as cur:
            cur.execute(sql, (*[enums.TestEnumOverrideMoodTest(v) for v in moods],))
            row = cur.fetchone()
        if row is None:
            return None
        return row[0]
