# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.8.0
# source file: queries_case.sql
"""Module containing queries from file queries_case.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = ("QueriesCase",)

import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import datetime
    import decimal
    import pymysql

from test.driver_pymysql.pydantic.classes import models


INSERT_CASE_ROW: typing.Final[str] = """-- name: InsertCaseRow :exec
INSERT INTO test_case_sensitivity (id, upper_dt, prec_dec) VALUES (%s, %s, %s)
"""

GET_CASE_ROW: typing.Final[str] = """-- name: GetCaseRow :one
SELECT id, upper_dt, prec_dec FROM test_case_sensitivity WHERE id = %s
"""

COUNT_CASE_ROWS: typing.Final[str] = """-- name: CountCaseRows :one
SELECT count(*) FROM test_case_sensitivity /*! WHERE id >= %s */
"""


class QueriesCase:
    """Queries from file queries_case.sql."""

    __slots__ = ("_conn",)

    def __init__(self, conn: pymysql.Connection) -> None:
        """Initialize the instance using the connection.

        Args:
            conn:
                Connection object of type `pymysql.Connection` used to execute the query.
        """
        self._conn = conn

    @property
    def conn(self) -> pymysql.Connection:
        """Connection object used to make queries.

        Returns:
            Connection object of type `pymysql.Connection` used to make queries.
        """
        return self._conn

    def insert_case_row(self, *, id_: int, upper_dt: datetime.datetime, prec_dec: decimal.Decimal) -> None:
        """Execute SQL query with `name: InsertCaseRow :exec`.

        ```sql
        INSERT INTO test_case_sensitivity (id, upper_dt, prec_dec) VALUES (%s, %s, %s)
        ```

        Args:
            id_: int.
            upper_dt: datetime.datetime.
            prec_dec: decimal.Decimal.
        """
        with self._conn.cursor() as cur:
            cur.execute(INSERT_CASE_ROW, (id_, upper_dt, prec_dec))

    def get_case_row(self, *, id_: int) -> models.TestCaseSensitivity | None:
        """Fetch one from the db using the SQL query with `name: GetCaseRow :one`.

        ```sql
        SELECT id, upper_dt, prec_dec FROM test_case_sensitivity WHERE id = %s
        ```

        Args:
            id_: int.

        Returns:
            Result of type `models.TestCaseSensitivity` fetched from the db. Will be `None` if not found.
        """
        with self._conn.cursor() as cur:
            cur.execute(GET_CASE_ROW, (id_,))
            row = cur.fetchone()
        if row is None:
            return None
        return models.TestCaseSensitivity(id_=row[0], upper_dt=row[1], prec_dec=row[2])

    def count_case_rows(self, *, id_: int) -> int | None:
        """Fetch one from the db using the SQL query with `name: CountCaseRows :one`.

        ```sql
        SELECT count(*) FROM test_case_sensitivity /*! WHERE id >= %s */
        ```

        Args:
            id_: int.

        Returns:
            Result of type `int` fetched from the db. Will be `None` if not found.
        """
        with self._conn.cursor() as cur:
            cur.execute(COUNT_CASE_ROWS, (id_,))
            row = cur.fetchone()
        if row is None:
            return None
        return row[0]
