# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.8.0
# source file: queries_named_slice.sql
"""Module containing queries from file queries_named_slice.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "QueryResults",
    "get_named_slice_row",
    "get_named_slice_rows",
    "get_named_slice_rows_arg_first",
    "get_named_slice_rows_reused",
)

import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import sqlite3

    type QueryResultsArgsType = int | float | str | memoryview | collections.abc.Sequence[QueryResultsArgsType] | None

from test.driver_sqlite3.dataclass.functions import models


GET_NAMED_SLICE_ROWS: typing.Final[str] = """-- name: GetNamedSliceRows :many

SELECT id, name, note FROM test_slice WHERE id IN (/*SLICE:ids*/?) AND name = ? ORDER BY id
"""

GET_NAMED_SLICE_ROWS_REUSED: typing.Final[str] = """-- name: GetNamedSliceRowsReused :many
SELECT id, name, note FROM test_slice WHERE id IN (/*SLICE:ids*/?) AND name = ? AND (note IS NULL OR name = ?) AND id IN (/*SLICE:ids*/?) ORDER BY id
"""

GET_NAMED_SLICE_ROWS_ARG_FIRST: typing.Final[str] = """-- name: GetNamedSliceRowsArgFirst :many
SELECT id, name, note FROM test_slice WHERE name = ? AND id IN (/*SLICE:ids*/?) ORDER BY id
"""

GET_NAMED_SLICE_ROW: typing.Final[str] = """-- name: GetNamedSliceRow :one
SELECT id, name, note FROM test_slice WHERE id IN (/*SLICE:ids*/?) AND name = ? ORDER BY id LIMIT 1
"""


class QueryResults[T]:
    """Helper class that allows both iteration and normal fetching of data from the db."""

    __slots__ = ("_args", "_conn", "_cursor", "_decode_hook", "_iterator", "_sql")

    def __init__(
        self,
        conn: sqlite3.Connection,
        sql: str,
        decode_hook: collections.abc.Callable[[sqlite3.Row], T],
        *args: QueryResultsArgsType,
    ) -> None:
        """Initialize the QueryResults instance.

        Args:
            conn:
                The connection object of type `sqlite3.Connection` used to execute queries.
            sql:
                The SQL statement that will be executed when fetching/iterating.
            decode_hook:
                A callback that turns an `sqlite3.Row` object into `T` that will be returned.
            *args:
                Arguments that should be sent when executing the sql query.
        """
        self._conn = conn
        self._sql = sql
        self._decode_hook = decode_hook
        self._args = args
        self._cursor: sqlite3.Cursor | None = None
        self._iterator: collections.abc.Iterator[sqlite3.Row] | None = None

    def __iter__(self) -> QueryResults[T]:
        """Initialize iteration support.

        Returns:
            Self as an iterator.
        """
        return self

    def __call__(
        self,
    ) -> collections.abc.Sequence[T]:
        """Allow calling the object to return all rows as a fully decoded sequence.

        Returns:
            A sequence of decoded objects of type `T`.
        """
        result = self._conn.execute(self._sql, self._args).fetchall()
        return [self._decode_hook(row) for row in result]

    def __next__(self) -> T:
        """Yield the next item in the query result using a sqlite3 cursor.

        Returns:
            The next decoded result of type `T`.

        Raises:
            StopIteration: When no more records are available.
        """
        if self._cursor is None or self._iterator is None:
            self._cursor: sqlite3.Cursor | None = self._conn.execute(self._sql, self._args)
            self._iterator = self._cursor.__iter__()
        try:
            record = self._iterator.__next__()
        except StopIteration:
            self._cursor = None
            self._iterator = None
            raise
        return self._decode_hook(record)


def get_named_slice_rows(conn: sqlite3.Connection, *, ids: collections.abc.Sequence[int], wanted: str) -> QueryResults[models.TestSlice]:
    """Fetch many from the db using the SQL query with `name: GetNamedSliceRows :many`.

    ```sql

    SELECT id, name, note FROM test_slice WHERE id IN (/*SLICE:ids*/?) AND name = ? ORDER BY id
    ```

    Args:
        conn:
            Connection object of type `sqlite3.Connection` used to execute the query.
        ids: collections.abc.Sequence[int].
        wanted: str.

    Returns:
        Helper class of type `QueryResults[models.TestSlice]` that allows both iteration and normal fetching of data from the db.
    """

    def _decode_hook(row: sqlite3.Row) -> models.TestSlice:
        return models.TestSlice(id_=row[0], name=row[1], note=row[2])

    sql = GET_NAMED_SLICE_ROWS.replace("/*SLICE:ids*/?", ",".join("?" * len(ids)) or "NULL", 1)
    return QueryResults(conn, sql, _decode_hook, *ids, wanted)


def get_named_slice_rows_reused(conn: sqlite3.Connection, *, ids: collections.abc.Sequence[int], wanted: str) -> QueryResults[models.TestSlice]:
    """Fetch many from the db using the SQL query with `name: GetNamedSliceRowsReused :many`.

    ```sql
    SELECT id, name, note FROM test_slice WHERE id IN (/*SLICE:ids*/?) AND name = ? AND (note IS NULL OR name = ?) AND id IN (/*SLICE:ids*/?) ORDER BY id
    ```

    Args:
        conn:
            Connection object of type `sqlite3.Connection` used to execute the query.
        ids: collections.abc.Sequence[int].
        wanted: str.

    Returns:
        Helper class of type `QueryResults[models.TestSlice]` that allows both iteration and normal fetching of data from the db.
    """

    def _decode_hook(row: sqlite3.Row) -> models.TestSlice:
        return models.TestSlice(id_=row[0], name=row[1], note=row[2])

    sql = GET_NAMED_SLICE_ROWS_REUSED.replace("/*SLICE:ids*/?", ",".join("?" * len(ids)) or "NULL")
    return QueryResults(conn, sql, _decode_hook, *ids, wanted, wanted, *ids)


def get_named_slice_rows_arg_first(conn: sqlite3.Connection, *, wanted: str, ids: collections.abc.Sequence[int]) -> QueryResults[models.TestSlice]:
    """Fetch many from the db using the SQL query with `name: GetNamedSliceRowsArgFirst :many`.

    ```sql
    SELECT id, name, note FROM test_slice WHERE name = ? AND id IN (/*SLICE:ids*/?) ORDER BY id
    ```

    Args:
        conn:
            Connection object of type `sqlite3.Connection` used to execute the query.
        wanted: str.
        ids: collections.abc.Sequence[int].

    Returns:
        Helper class of type `QueryResults[models.TestSlice]` that allows both iteration and normal fetching of data from the db.
    """

    def _decode_hook(row: sqlite3.Row) -> models.TestSlice:
        return models.TestSlice(id_=row[0], name=row[1], note=row[2])

    sql = GET_NAMED_SLICE_ROWS_ARG_FIRST.replace("/*SLICE:ids*/?", ",".join("?" * len(ids)) or "NULL", 1)
    return QueryResults(conn, sql, _decode_hook, wanted, *ids)


def get_named_slice_row(conn: sqlite3.Connection, *, ids: collections.abc.Sequence[int], wanted: str) -> models.TestSlice | None:
    """Fetch one from the db using the SQL query with `name: GetNamedSliceRow :one`.

    ```sql
    SELECT id, name, note FROM test_slice WHERE id IN (/*SLICE:ids*/?) AND name = ? ORDER BY id LIMIT 1
    ```

    Args:
        conn:
            Connection object of type `sqlite3.Connection` used to execute the query.
        ids: collections.abc.Sequence[int].
        wanted: str.

    Returns:
        Result of type `models.TestSlice` fetched from the db. Will be `None` if not found.
    """
    sql = GET_NAMED_SLICE_ROW.replace("/*SLICE:ids*/?", ",".join("?" * len(ids)) or "NULL", 1)
    row = conn.execute(sql, (*ids, wanted)).fetchone()
    if row is None:
        return None
    return models.TestSlice(id_=row[0], name=row[1], note=row[2])
