# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.8.0
# source file: queries_backslash.sql
"""Module containing queries from file queries_backslash.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "get_backslash_note",
    "get_backslash_pattern",
    "insert_backslash_row",
)

import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import sqlite3


INSERT_BACKSLASH_ROW: typing.Final[str] = """-- name: InsertBackslashRow :exec

INSERT INTO test_slice (id, name, note) VALUES (?, ?, ?)
"""

GET_BACKSLASH_PATTERN: typing.Final[str] = r"""-- name: GetBackslashPattern :one
SELECT 'a\tb\d+' AS pattern
"""

GET_BACKSLASH_NOTE: typing.Final[str] = r"""-- name: GetBackslashNote :one
SELECT note FROM test_slice WHERE note = 'C:\dir\name' AND id = ?
"""


def insert_backslash_row(conn: sqlite3.Connection, *, id_: int, name: str, note: str | None) -> None:
    """Execute SQL query with `name: InsertBackslashRow :exec`.

    ```sql

    INSERT INTO test_slice (id, name, note) VALUES (?, ?, ?)
    ```

    Args:
        conn:
            Connection object of type `sqlite3.Connection` used to execute the query.
        id_: int.
        name: str.
        note: str | None.
    """
    conn.execute(INSERT_BACKSLASH_ROW, (id_, name, note))


def get_backslash_pattern(conn: sqlite3.Connection) -> str | None:
    r"""Fetch one from the db using the SQL query with `name: GetBackslashPattern :one`.

    ```sql
    SELECT 'a\tb\d+' AS pattern
    ```

    Args:
        conn:
            Connection object of type `sqlite3.Connection` used to execute the query.

    Returns:
        Result of type `str` fetched from the db. Will be `None` if not found.
    """
    row = conn.execute(GET_BACKSLASH_PATTERN).fetchone()
    if row is None:
        return None
    return row[0]


def get_backslash_note(conn: sqlite3.Connection, *, id_: int) -> str | None:
    r"""Fetch one from the db using the SQL query with `name: GetBackslashNote :one`.

    ```sql
    SELECT note FROM test_slice WHERE note = 'C:\dir\name' AND id = ?
    ```

    Args:
        conn:
            Connection object of type `sqlite3.Connection` used to execute the query.
        id_: int.

    Returns:
        Result of type `str` fetched from the db. Will be `None` if not found.
    """
    row = conn.execute(GET_BACKSLASH_NOTE, (id_,)).fetchone()
    if row is None:
        return None
    return row[0]
