# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
#   sqlc-gen-better-python v0.3.1
"""Module containing models."""
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "TestInnerSqliteType",
    "TestSqliteType",
)

import attrs
import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import datetime
    import decimal



@attrs.define()
class TestInnerSqliteType:
    """Model representing TestInnerSqliteType.

    Attributes
    ----------
    table_id : int
    int_test : int
    bigint_test : int
    smallint_test : int
    tinyint_test : int
    int2_test : int
    int8_test : int
    bigserial_test : int
    blob_test : memoryview
    real_test : float
    double_test : float
    double_precision_test : float
    float_test : float
    numeric_test : float
    decimal_test : decimal.Decimal
    boolean_test : bool
    bool_test : bool
    date_test : datetime.date
    datetime_test : datetime.datetime
    timestamp_test : datetime.datetime
    character_test : str
    varchar_test : str
    varyingcharacter_test : str
    nchar_test : str
    nativecharacter_test : str
    nvarchar_test : str
    text_test : str
    clob_test : str
    json_test : str

    """

    table_id: int
    int_test: int
    bigint_test: int
    smallint_test: int
    tinyint_test: int
    int2_test: int
    int8_test: int
    bigserial_test: int
    blob_test: memoryview
    real_test: float
    double_test: float
    double_precision_test: float
    float_test: float
    numeric_test: float
    decimal_test: decimal.Decimal
    boolean_test: bool
    bool_test: bool
    date_test: datetime.date
    datetime_test: datetime.datetime
    timestamp_test: datetime.datetime
    character_test: str
    varchar_test: str
    varyingcharacter_test: str
    nchar_test: str
    nativecharacter_test: str
    nvarchar_test: str
    text_test: str
    clob_test: str
    json_test: str


@attrs.define()
class TestSqliteType:
    """Model representing TestSqliteType.

    Attributes
    ----------
    id : int
    int_test : int
    bigint_test : int
    smallint_test : int
    tinyint_test : int
    int2_test : int
    int8_test : int
    bigserial_test : int
    blob_test : memoryview
    real_test : float
    double_test : float
    double_precision_test : float
    float_test : float
    numeric_test : float
    decimal_test : decimal.Decimal
    boolean_test : bool
    bool_test : bool
    date_test : datetime.date
    datetime_test : datetime.datetime
    timestamp_test : datetime.datetime
    character_test : str
    varchar_test : str
    varyingcharacter_test : str
    nchar_test : str
    nativecharacter_test : str
    nvarchar_test : str
    text_test : str
    clob_test : str
    json_test : str

    """

    id: int
    int_test: int
    bigint_test: int
    smallint_test: int
    tinyint_test: int
    int2_test: int
    int8_test: int
    bigserial_test: int
    blob_test: memoryview
    real_test: float
    double_test: float
    double_precision_test: float
    float_test: float
    numeric_test: float
    decimal_test: decimal.Decimal
    boolean_test: bool
    bool_test: bool
    date_test: datetime.date
    datetime_test: datetime.datetime
    timestamp_test: datetime.datetime
    character_test: str
    varchar_test: str
    varyingcharacter_test: str
    nchar_test: str
    nativecharacter_test: str
    nvarchar_test: str
    text_test: str
    clob_test: str
    json_test: str
