# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
#   sqlc-gen-better-python v0.3.1
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "TestInnerPostgresType",
    "TestPostgresType",
)

import typing

import attrs

if typing.TYPE_CHECKING:
    import collections.abc
    import datetime
    import decimal
    import uuid



@attrs.define()
class TestInnerPostgresType:
    table_id: int = attrs.field()
    serial_test: int = attrs.field()
    serial4_test: int = attrs.field()
    bigserial_test: int = attrs.field()
    smallserial_test: int = attrs.field()
    int_test: int = attrs.field()
    bigint_test: int = attrs.field()
    smallint_test: int = attrs.field()
    float_test: float = attrs.field()
    double_precision_test: float = attrs.field()
    real_test: float = attrs.field()
    numeric_test: decimal.Decimal = attrs.field()
    money_test: str = attrs.field()
    bool_test: bool = attrs.field()
    json_test: str = attrs.field()
    jsonb_test: str = attrs.field()
    bytea_test: memoryview = attrs.field()
    date_test: datetime.date = attrs.field()
    time_test: datetime.time = attrs.field()
    timetz_test: datetime.time = attrs.field()
    timestamp_test: datetime.datetime = attrs.field()
    timestamptz_test: datetime.datetime = attrs.field()
    interval_test: datetime.timedelta = attrs.field()
    text_test: str = attrs.field()
    varchar_test: str = attrs.field()
    bpchar_test: str = attrs.field()
    char_test: str = attrs.field()
    citext_test: str = attrs.field()
    uuid_test: uuid.UUID = attrs.field()
    inet_test: str = attrs.field()
    cidr_test: str = attrs.field()
    macaddr_test: str = attrs.field()
    macaddr8_test: str = attrs.field()
    ltree_test: str = attrs.field()
    lquery_test: str = attrs.field()
    ltxtquery_test: str = attrs.field()


@attrs.define()
class TestPostgresType:
    id: int = attrs.field()
    serial_test: int = attrs.field()
    serial4_test: int = attrs.field()
    bigserial_test: int = attrs.field()
    smallserial_test: int = attrs.field()
    int_test: int = attrs.field()
    bigint_test: int = attrs.field()
    smallint_test: int = attrs.field()
    float_test: float = attrs.field()
    double_precision_test: float = attrs.field()
    real_test: float = attrs.field()
    numeric_test: decimal.Decimal = attrs.field()
    money_test: str = attrs.field()
    bool_test: bool = attrs.field()
    json_test: str = attrs.field()
    jsonb_test: str = attrs.field()
    bytea_test: memoryview = attrs.field()
    date_test: datetime.date = attrs.field()
    time_test: datetime.time = attrs.field()
    timetz_test: datetime.time = attrs.field()
    timestamp_test: datetime.datetime = attrs.field()
    timestamptz_test: datetime.datetime = attrs.field()
    interval_test: datetime.timedelta = attrs.field()
    text_test: str = attrs.field()
    varchar_test: str = attrs.field()
    bpchar_test: str = attrs.field()
    char_test: str = attrs.field()
    citext_test: str = attrs.field()
    uuid_test: uuid.UUID = attrs.field()
    inet_test: str = attrs.field()
    cidr_test: str = attrs.field()
    macaddr_test: str = attrs.field()
    macaddr8_test: str = attrs.field()
    ltree_test: str = attrs.field()
    lquery_test: str = attrs.field()
    ltxtquery_test: str = attrs.field()
