# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
#   sqlc-gen-better-python v0.4.6
# source file: queries_invalid_identifiers.sql
"""Module containing queries from file queries_invalid_identifiers.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "get_invalid_identifiers",
    "insert_invalid_identifiers",
)

import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import collections.abc

    type ConnectionLike = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from test.driver_asyncpg.attrs.functions import models


INSERT_INVALID_IDENTIFIERS: typing.Final[str] = """-- name: InsertInvalidIdentifiers :exec
INSERT INTO test_invalid_identifiers (id, "3p%", "new notes") VALUES ($1, $2, $3)
"""

GET_INVALID_IDENTIFIERS: typing.Final[str] = """-- name: GetInvalidIdentifiers :one
SELECT id, "3p%", "new notes", "%pct" FROM test_invalid_identifiers WHERE id = $1
"""


async def insert_invalid_identifiers(conn: ConnectionLike, *, id_: int, arg_3p_: str | None, new_notes: str) -> None:
    """Execute SQL query with `name: InsertInvalidIdentifiers :exec`.

    ```sql
    INSERT INTO test_invalid_identifiers (id, "3p%", "new notes") VALUES ($1, $2, $3)
    ```

    Parameters
    ----------
    conn : ConnectionLike
        Connection object of type `ConnectionLike` used to execute the query.
    id_ : int
    arg_3p_ : str | None
    new_notes : str

    """
    await conn.execute(INSERT_INVALID_IDENTIFIERS, id_, arg_3p_, new_notes)


async def get_invalid_identifiers(conn: ConnectionLike, *, id_: int) -> models.TestInvalidIdentifier | None:
    """Fetch one from the db using the SQL query with `name: GetInvalidIdentifiers :one`.

    ```sql
    SELECT id, "3p%", "new notes", "%pct" FROM test_invalid_identifiers WHERE id = $1
    ```

    Parameters
    ----------
    conn : ConnectionLike
        Connection object of type `ConnectionLike` used to execute the query.
    id_ : int

    Returns
    -------
    models.TestInvalidIdentifier
        Result fetched from the db. Will be `None` if not found.

    """
    row = await conn.fetchrow(GET_INVALID_IDENTIFIERS, id_)
    if row is None:
        return None
    return models.TestInvalidIdentifier(id_=row[0], column_3p_=row[1], new_notes=row[2], column__pct=row[3])
