# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.8.0
"""Module containing models."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = ("TestDbtypeOverride",)

import dataclasses
import typing

if typing.TYPE_CHECKING:
    import collections.abc


@dataclasses.dataclass()
class TestDbtypeOverride:
    """Model representing TestDbtypeOverride.

    Attributes:
        id_: int
        happened_at: str
    """

    id_: int
    happened_at: str
