# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.8.0
# source file: queries_dbtype_override.sql
"""Module containing queries from file queries_dbtype_override.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "get_dbtype_override",
    "insert_dbtype_override",
)

import test.converters
import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import pymysql

from test.driver_pymysql.dbtype.functions import models


INSERT_DBTYPE_OVERRIDE: typing.Final[str] = """-- name: InsertDbtypeOverride :exec
INSERT INTO test_dbtype_override (id, happened_at) VALUES (%s, %s)
"""

GET_DBTYPE_OVERRIDE: typing.Final[str] = """-- name: GetDbtypeOverride :one
SELECT id, happened_at FROM test_dbtype_override WHERE id = %s
"""


def insert_dbtype_override(conn: pymysql.Connection, *, id_: int, happened_at: str) -> None:
    """Execute SQL query with `name: InsertDbtypeOverride :exec`.

    ```sql
    INSERT INTO test_dbtype_override (id, happened_at) VALUES (%s, %s)
    ```

    Args:
        conn:
            Connection object of type `pymysql.Connection` used to execute the query.
        id_: int.
        happened_at: str.
    """
    with conn.cursor() as cur:
        cur.execute(INSERT_DBTYPE_OVERRIDE, (id_, test.converters.encode_stamp(happened_at)))


def get_dbtype_override(conn: pymysql.Connection, *, id_: int) -> models.TestDbtypeOverride | None:
    """Fetch one from the db using the SQL query with `name: GetDbtypeOverride :one`.

    ```sql
    SELECT id, happened_at FROM test_dbtype_override WHERE id = %s
    ```

    Args:
        conn:
            Connection object of type `pymysql.Connection` used to execute the query.
        id_: int.

    Returns:
        Result of type `models.TestDbtypeOverride` fetched from the db. Will be `None` if not found.
    """
    with conn.cursor() as cur:
        cur.execute(GET_DBTYPE_OVERRIDE, (id_,))
        row = cur.fetchone()
    if row is None:
        return None
    return models.TestDbtypeOverride(id_=row[0], happened_at=test.converters.decode_stamp(row[1]))
