package writer

import (
	"cmp"
	"fmt"
	"os"
	"slices"
	"strings"

	"github.com/rayakame/sqlc-gen-better-python/internal/config"
	"github.com/rayakame/sqlc-gen-better-python/internal/model"
	"github.com/rayakame/sqlc-gen-better-python/internal/utils"
)

type CodeWriter struct {
	QueryResults *QueryResultsWriter

	builder strings.Builder

	indentChar          string
	charsPerIndentLevel int

	docstringOmitSQL    bool
	docstringConvention config.DocstringConvention
	docstringDriver     config.SQLDriver

	omitTypeChecking bool
}

func NewCodeWriter(
	config *config.Config,
) *CodeWriter {
	w := utils.ToPtr(CodeWriter{
		builder:             strings.Builder{},
		indentChar:          config.IndentChar,
		charsPerIndentLevel: config.CharsPerIndentLevel,
		docstringConvention: config.EmitDocstrings,
		docstringDriver:     config.SqlDriver,
		docstringOmitSQL:    !*config.EmitDocstringsSQL,
		omitTypeChecking:    config.OmitTypecheckingBlock,
		QueryResults:        nil,
	})
	w.QueryResults = NewQueryResultsWriter(w)
	return w
}

// WriteIndentedString writes indented text without a trailing newline.
func (w *CodeWriter) WriteIndentedString(level int, txt string) {
	w.WriteString(w.indent(level) + txt)
}

// WriteLine writes text followed by a newline.
func (w *CodeWriter) WriteLine(txt string) {
	w.WriteString(txt)
	w.WriteString("\n")
}

// WriteIndentedLine writes indented text followed by a newline.
func (w *CodeWriter) WriteIndentedLine(level int, txt string) {
	w.WriteIndentedString(level, txt)
	w.WriteString("\n")
}

// NewLine writes a single newline.
func (w *CodeWriter) NewLine() {
	w.WriteString("\n")
}

// NNewLine writes n newlines.
func (w *CodeWriter) NNewLine(n int) {
	for range n {
		w.WriteString("\n")
	}
}

// WriteSqlcHeader writes the "generated by sqlc" comment block.
func (w *CodeWriter) WriteSqlcHeader(query *model.Query) {
	sqlcVersion := os.Getenv("SQLC_VERSION")

	w.WriteLine("# Code generated by sqlc. DO NOT EDIT.")
	w.WriteLine("# versions:")
	w.WriteLine("#   sqlc " + sqlcVersion)
	w.WriteLine("#   sqlc-gen-better-python " + config.PluginVersion)
	if query != nil {
		w.WriteLine("# source file: " + query.FileName)
	}
}

// WriteFutureImport writes the future-annotations import that follows the
// header (and module docstring, if any).
func (w *CodeWriter) WriteFutureImport() {
	w.WriteLine("from __future__ import annotations")
	w.NewLine()
}

func (w *CodeWriter) WriteString(txt string) {
	// strings.Builder.WriteString is documented to always return a nil error.
	w.builder.WriteString(txt) //nolint:errcheck // never returns an error
}

func (w *CodeWriter) Bytes() []byte {
	return []byte(w.builder.String())
}

func (w *CodeWriter) String() string {
	return w.builder.String()
}

func (w *CodeWriter) WriteAll(items []string) {
	slices.SortFunc(items, cmp.Compare)
	// A single-element tuple's trailing comma is required syntax, so ruff
	// format collapses it onto one line; match that.
	if len(items) == 1 {
		w.WriteLine(fmt.Sprintf(`__all__: collections.abc.Sequence[str] = ("%s",)`, items[0]))

		return
	}
	w.WriteLine("__all__: collections.abc.Sequence[str] = (")
	for _, item := range items {
		w.WriteIndentedLine(1, fmt.Sprintf(`"%s",`, item))
	}
	w.WriteLine(")")
}

// MaxLineLength is the ruff line-length limit (ruff's maximum allowed value).
// Statements the generator would render longer than this are exploded with
// magic trailing commas so that ruff format leaves them untouched.
const MaxLineLength = 320

// FitsLine reports whether txt fits within MaxLineLength at the indent level.
func (w *CodeWriter) FitsLine(indent int, txt string) bool {
	return len(w.indent(indent))+len(txt) <= MaxLineLength
}

// WriteWrappedCall writes head+args+tail on a single line when it fits,
// otherwise one argument per line with trailing commas. head must end with
// the opening parenthesis, tail must start with the closing one.
func (w *CodeWriter) WriteWrappedCall(indent int, head string, args []string, tail string) {
	single := head + strings.Join(args, ", ") + tail
	if w.FitsLine(indent, single) {
		w.WriteIndentedLine(indent, single)

		return
	}
	w.WriteIndentedLine(indent, head)
	for _, arg := range args {
		w.WriteIndentedLine(indent+1, arg+",")
	}
	w.WriteIndentedLine(indent, tail)
}

// indent returns the indentation string for the given level.
func (w *CodeWriter) indent(level int) string {
	return strings.Repeat(w.indentChar, level*w.charsPerIndentLevel)
}
