package writer_test

import (
	"strings"
	"testing"

	"github.com/rayakame/sqlc-gen-better-python/internal/config"
	"github.com/rayakame/sqlc-gen-better-python/internal/model"
	"github.com/rayakame/sqlc-gen-better-python/internal/utils"
	"github.com/rayakame/sqlc-gen-better-python/internal/writer"
)

// indentWidth mirrors the chars_per_indent_level used by newWriter.
const indentWidth = 4

func newWriter(convention config.DocstringConvention) *writer.CodeWriter {
	return writer.NewCodeWriter(&config.Config{
		SqlDriver:           config.SQLDriverAsyncpg,
		EmitDocstrings:      convention,
		EmitDocstringsSQL:   utils.ToPtr(true),
		IndentChar:          " ",
		CharsPerIndentLevel: indentWidth,
	})
}

func TestNewCodeWriter(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name       string
		indentChar string
		width      int
		level      int
		want       string
	}{
		{name: "four spaces per level", indentChar: " ", width: 4, level: 1, want: "    x\n"},
		{name: "tab char width one", indentChar: "\t", width: 1, level: 2, want: "\t\tx\n"},
		{name: "two spaces level three", indentChar: " ", width: 2, level: 3, want: "      x\n"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			w := writer.NewCodeWriter(&config.Config{
				SqlDriver:           config.SQLDriverAsyncpg,
				EmitDocstrings:      config.DocstringConventionNone,
				EmitDocstringsSQL:   utils.ToPtr(true),
				IndentChar:          tc.indentChar,
				CharsPerIndentLevel: tc.width,
			})
			if w.QueryResults == nil {
				t.Fatal("NewCodeWriter() QueryResults = nil, want non-nil")
			}
			w.WriteIndentedLine(tc.level, "x")
			if got := w.String(); got != tc.want {
				t.Errorf("WriteIndentedLine(%d, \"x\") wrote %q, want %q", tc.level, got, tc.want)
			}
		})
	}
}

func TestCodeWriterBasics(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name  string
		build func(w *writer.CodeWriter)
		want  string
	}{
		{name: "WriteString", build: func(w *writer.CodeWriter) { w.WriteString("raw") }, want: "raw"},
		{name: "WriteLine", build: func(w *writer.CodeWriter) { w.WriteLine("a = 1") }, want: "a = 1\n"},
		{
			name:  "WriteIndentedString no newline",
			build: func(w *writer.CodeWriter) { w.WriteIndentedString(1, "a") },
			want:  "    a",
		},
		{
			name:  "WriteIndentedLine level two",
			build: func(w *writer.CodeWriter) { w.WriteIndentedLine(2, "a") },
			want:  "        a\n",
		},
		{name: "NewLine", build: func(w *writer.CodeWriter) { w.NewLine() }, want: "\n"},
		{name: "NNewLine zero", build: func(w *writer.CodeWriter) { w.NNewLine(0) }, want: ""},
		{name: "NNewLine three", build: func(w *writer.CodeWriter) { w.NNewLine(3) }, want: "\n\n\n"},
		{
			name:  "WriteFutureImport",
			build: func(w *writer.CodeWriter) { w.WriteFutureImport() },
			want:  "from __future__ import annotations\n\n",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			w := newWriter(config.DocstringConventionNone)
			tc.build(w)
			if got := w.String(); got != tc.want {
				t.Errorf("String() = %q, want %q", got, tc.want)
			}
			if got := string(w.Bytes()); got != tc.want {
				t.Errorf("Bytes() = %q, want %q", got, tc.want)
			}
		})
	}
}

func TestWriteSqlcHeader(t *testing.T) {
	// t.Setenv is incompatible with t.Parallel, so this test runs serially.
	t.Run("with version and source query", func(t *testing.T) {
		t.Setenv("SQLC_VERSION", "v1.29.0")
		w := newWriter(config.DocstringConventionNone)
		w.WriteSqlcHeader(&model.Query{FileName: "queries.sql"})
		want := strings.Join([]string{
			"# Code generated by sqlc. DO NOT EDIT.",
			"# versions:",
			"#   sqlc v1.29.0",
			"#   sqlc-gen-better-python " + config.PluginVersion,
			"# source file: queries.sql",
			"",
		}, "\n")
		if got := w.String(); got != want {
			t.Errorf("WriteSqlcHeader() = %q, want %q", got, want)
		}
	})
	t.Run("without version and nil query", func(t *testing.T) {
		t.Setenv("SQLC_VERSION", "")
		w := newWriter(config.DocstringConventionNone)
		w.WriteSqlcHeader(nil)
		want := strings.Join([]string{
			"# Code generated by sqlc. DO NOT EDIT.",
			"# versions:",
			"#   sqlc ",
			"#   sqlc-gen-better-python " + config.PluginVersion,
			"",
		}, "\n")
		if got := w.String(); got != want {
			t.Errorf("WriteSqlcHeader() = %q, want %q", got, want)
		}
	})
}

func TestWriteAll(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name  string
		items []string
		want  string
	}{
		{name: "empty tuple", items: nil, want: "__all__: collections.abc.Sequence[str] = ()\n"},
		{
			name:  "single element collapses onto one line",
			items: []string{"Author"},
			want:  "__all__: collections.abc.Sequence[str] = (\"Author\",)\n",
		},
		{
			name:  "multiple elements sorted and exploded",
			items: []string{"Beta", "Alpha"},
			want: strings.Join([]string{
				"__all__: collections.abc.Sequence[str] = (",
				"    \"Alpha\",",
				"    \"Beta\",",
				")",
				"",
			}, "\n"),
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			w := newWriter(config.DocstringConventionNone)
			w.WriteAll(tc.items)
			if got := w.String(); got != tc.want {
				t.Errorf("WriteAll(%v) = %q, want %q", tc.items, got, tc.want)
			}
		})
	}
}

func TestFitsLine(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name   string
		indent int
		length int
		want   bool
	}{
		{name: "exactly at limit", indent: 0, length: writer.MaxLineLength, want: true},
		{name: "one over limit", indent: 0, length: writer.MaxLineLength + 1, want: false},
		{name: "indent counts toward limit", indent: 1, length: writer.MaxLineLength - indentWidth, want: true},
		{name: "indent pushes over limit", indent: 1, length: writer.MaxLineLength - indentWidth + 1, want: false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			w := newWriter(config.DocstringConventionNone)
			txt := strings.Repeat("a", tc.length)
			if got := w.FitsLine(tc.indent, txt); got != tc.want {
				t.Errorf("FitsLine(%d, len %d) = %v, want %v", tc.indent, tc.length, got, tc.want)
			}
		})
	}
}

func TestWriteWrappedCall(t *testing.T) {
	t.Parallel()
	longArg := strings.Repeat("b", writer.MaxLineLength)
	cases := []struct {
		name   string
		indent int
		head   string
		args   []string
		tail   string
		want   string
	}{
		{
			name:   "fits on one line",
			indent: 1,
			head:   "self.foo(",
			args:   []string{"a", "b"},
			tail:   ")",
			want:   "    self.foo(a, b)\n",
		},
		{
			name:   "exploded with trailing commas",
			indent: 1,
			head:   "self.foo(",
			args:   []string{"a", longArg},
			tail:   ")",
			want: strings.Join([]string{
				"    self.foo(",
				"        a,",
				"        " + longArg + ",",
				"    )",
				"",
			}, "\n"),
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			w := newWriter(config.DocstringConventionNone)
			w.WriteWrappedCall(tc.indent, tc.head, tc.args, tc.tail)
			if got := w.String(); got != tc.want {
				t.Errorf("WriteWrappedCall() = %q, want %q", got, tc.want)
			}
		})
	}
}

func TestPyQuote(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name string
		in   string
		want string
	}{
		{name: "empty value", in: "", want: `""`},
		{name: "plain value", in: "hello", want: `"hello"`},
		{name: "escapes stay go-style", in: "line\nbreak", want: `"line\nbreak"`},
		{name: "double quotes flip outer to single", in: `say "hi"`, want: `'say "hi"'`},
		{name: "single quote keeps double quotes", in: "it's", want: `"it's"`},
		{name: "both quote kinds keep double quotes", in: `mix "d" and 's'`, want: `"mix \"d\" and 's'"`},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			if got := writer.PyQuote(tc.in); got != tc.want {
				t.Errorf("PyQuote(%q) = %s, want %s", tc.in, got, tc.want)
			}
		})
	}
}
