package writer

import (
	"cmp"
	"fmt"
	"os"
	"slices"
	"strings"

	"github.com/rayakame/sqlc-gen-better-python/internal/config"
	"github.com/rayakame/sqlc-gen-better-python/internal/log"
	"github.com/rayakame/sqlc-gen-better-python/internal/model"
	"github.com/rayakame/sqlc-gen-better-python/internal/utils"
)

type CodeWriter struct {
	QueryResults *QueryResultsWriter

	builder strings.Builder

	indentChar          string
	charsPerIndentLevel int

	docstringOmitSQL    bool
	docstringConvention config.DocstringConvention
	docstringDriver     config.SQLDriver

	omitTypeChecking bool
}

func NewCodeWriter(
	config *config.Config,
) *CodeWriter {
	w := utils.ToPtr(CodeWriter{
		builder:             strings.Builder{},
		indentChar:          config.IndentChar,
		charsPerIndentLevel: config.CharsPerIndentLevel,
		docstringConvention: config.EmitDocstrings,
		docstringDriver:     config.SqlDriver,
		docstringOmitSQL:    !*config.EmitDocstringsSQL,
		omitTypeChecking:    config.OmitTypecheckingBlock,
		QueryResults:        nil,
	})
	w.QueryResults = NewQueryResultsWriter(w)
	return w
}

// WriteIndentedString writes indented text without a trailing newline.
func (w *CodeWriter) WriteIndentedString(level int, txt string) {
	w.WriteString(w.indent(level) + txt)
}

// WriteLine writes text followed by a newline.
func (w *CodeWriter) WriteLine(txt string) {
	w.WriteString(txt)
	w.WriteString("\n")
}

// WriteIndentedLine writes indented text followed by a newline.
func (w *CodeWriter) WriteIndentedLine(level int, txt string) {
	w.WriteIndentedString(level, txt)
	w.WriteString("\n")
}

// NewLine writes a single newline.
func (w *CodeWriter) NewLine() {
	w.WriteString("\n")
}

// NNewLine writes n newlines.
func (w *CodeWriter) NNewLine(n int) {
	for range n {
		w.WriteString("\n")
	}
}

// WriteSqlcHeader writes the "generated by sqlc" comment block.
func (w *CodeWriter) WriteSqlcHeader(query *model.Query) {
	sqlcVersion := os.Getenv("SQLC_VERSION")

	w.WriteLine("# Code generated by sqlc. DO NOT EDIT.")
	w.WriteLine("# versions:")
	w.WriteLine("#   sqlc " + sqlcVersion)
	w.WriteLine("#   sqlc-gen-better-python " + config.PluginVersion)
	if query != nil {
		w.WriteLine("# source file: " + query.FileName)
	}
}

// WriteFutureImport writes the future-annotations import that follows the
// header (and module docstring, if any).
func (w *CodeWriter) WriteFutureImport() {
	w.WriteLine("from __future__ import annotations")
	w.NewLine()
}

func (w *CodeWriter) WriteString(txt string) {
	_, err := w.builder.WriteString(txt)
	if err != nil {
		log.L().LogErr("Error while trying to write string", err)
	}
}

func (w *CodeWriter) Bytes() []byte {
	return []byte(w.builder.String())
}

func (w *CodeWriter) String() string {
	return w.builder.String()
}

func (w *CodeWriter) WriteAll(items []string) {
	slices.SortFunc(items, func(a, b string) int {
		return cmp.Compare(a, b)
	})
	w.WriteLine("__all__: collections.abc.Sequence[str] = (")
	for _, item := range items {
		w.WriteIndentedLine(1, fmt.Sprintf(`"%s",`, item))
	}
	w.WriteLine(")")
}

// indent returns the indentation string for the given level.
func (w *CodeWriter) indent(level int) string {
	return strings.Repeat(w.indentChar, level*w.charsPerIndentLevel)
}
