# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.8.0
"""Module containing enums."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "TestInnerMysqlTypesMood",
    "TestInnerMysqlTypesTag",
    "TestMysqlTypesMood",
    "TestMysqlTypesTag",
)

import enum
import typing

if typing.TYPE_CHECKING:
    import collections.abc


class TestInnerMysqlTypesMood(enum.StrEnum):
    """Enum representing TestInnerMysqlTypesMood."""

    SAD = "sad"
    OK = "ok"
    HAPPY = "happy"
    VALUE_24H = "24h"
    VALUE__HIDDEN = "_hidden"


class TestInnerMysqlTypesTag(enum.StrEnum):
    """Enum representing TestInnerMysqlTypesTag."""

    ALPHA = "alpha"
    BETA = "beta"
    GAMMA = "gamma"


class TestMysqlTypesMood(enum.StrEnum):
    """Enum representing TestMysqlTypesMood."""

    SAD = "sad"
    OK = "ok"
    HAPPY = "happy"
    VALUE_24H = "24h"
    VALUE__HIDDEN = "_hidden"


class TestMysqlTypesTag(enum.StrEnum):
    """Enum representing TestMysqlTypesTag."""

    ALPHA = "alpha"
    BETA = "beta"
    GAMMA = "gamma"
