# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.6.0
# source file: queries_copy_override.sql
"""Module containing queries from file queries_copy_override.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "CopyOverrideRowsParams",
    "copy_override_rows",
    "count_copy_override_rows",
    "delete_copy_override_rows",
)

import attrs
import decimal
import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import psycopg
    import psycopg.rows

    type ConnectionLike = psycopg.AsyncConnection[psycopg.rows.TupleRow]


@attrs.define()
class CopyOverrideRowsParams:
    """Model representing CopyOverrideRowsParams.

    Attributes
    ----------
    id_ : int
    amount : float
    co_l : str

    """

    id_: int
    amount: float
    co_l: str


COPY_OVERRIDE_ROWS: typing.Final[typing.LiteralString] = """-- name: CopyOverrideRows :copyfrom
INSERT INTO test_copy_override (id, amount, "co""l") VALUES ($1, $2, $3)
"""

COUNT_COPY_OVERRIDE_ROWS: typing.Final[typing.LiteralString] = """-- name: CountCopyOverrideRows :one
SELECT count(*) FROM test_copy_override
"""

DELETE_COPY_OVERRIDE_ROWS: typing.Final[typing.LiteralString] = """-- name: DeleteCopyOverrideRows :exec
DELETE FROM test_copy_override
"""


async def copy_override_rows(conn: ConnectionLike, *, params: collections.abc.Sequence[CopyOverrideRowsParams]) -> int:
    """Execute COPY FROM query to insert rows into a table with `name: CopyOverrideRows :copyfrom` and return the number of affected rows.

    Parameters
    ----------
    conn : ConnectionLike
        Connection object of type `ConnectionLike` used to execute the query.
    params : collections.abc.Sequence[CopyOverrideRowsParams]
        A list of params for rows that should be inserted.

    Returns
    -------
    int
        The number of affected rows.

    """
    async with conn.cursor() as cur:
        async with cur.copy('COPY "test_copy_override" ("id", "amount", "co""l") FROM STDIN') as copy:
            for param in params:
                await copy.write_row((param.id_, decimal.Decimal(param.amount), param.co_l))
        return cur.rowcount


async def count_copy_override_rows(conn: ConnectionLike) -> int | None:
    """Fetch one from the db using the SQL query with `name: CountCopyOverrideRows :one`.

    ```sql
    SELECT count(*) FROM test_copy_override
    ```

    Parameters
    ----------
    conn : ConnectionLike
        Connection object of type `ConnectionLike` used to execute the query.

    Returns
    -------
    int
        Result fetched from the db. Will be `None` if not found.

    """
    row = await (await conn.execute(COUNT_COPY_OVERRIDE_ROWS)).fetchone()
    if row is None:
        return None
    return row[0]


async def delete_copy_override_rows(conn: ConnectionLike) -> None:
    """Execute SQL query with `name: DeleteCopyOverrideRows :exec`.

    ```sql
    DELETE FROM test_copy_override
    ```

    Parameters
    ----------
    conn : ConnectionLike
        Connection object of type `ConnectionLike` used to execute the query.

    """
    await conn.execute(DELETE_COPY_OVERRIDE_ROWS)
