# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.6.0
# source file: queries_invalid_identifiers.sql
"""Module containing queries from file queries_invalid_identifiers.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "get_invalid_identifiers",
    "get_third_party_stat",
    "insert_invalid_identifiers",
    "insert_third_party_stat",
)

import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import collections.abc

    type ConnectionLike = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from test.driver_asyncpg.pydantic.functions import models


INSERT_INVALID_IDENTIFIERS: typing.Final[str] = """-- name: InsertInvalidIdentifiers :exec
INSERT INTO test_invalid_identifiers (id, "3p%", "new notes") VALUES ($1, $2, $3)
"""

GET_INVALID_IDENTIFIERS: typing.Final[str] = """-- name: GetInvalidIdentifiers :one
SELECT id, "3p%", "new notes", "%pct" FROM test_invalid_identifiers WHERE id = $1
"""

INSERT_THIRD_PARTY_STAT: typing.Final[str] = """-- name: InsertThirdPartyStat :exec
INSERT INTO "3rd_party_stats" (id, total) VALUES ($1, $2)
"""

GET_THIRD_PARTY_STAT: typing.Final[str] = """-- name: GetThirdPartyStat :one
SELECT id, total FROM "3rd_party_stats" WHERE id = $1
"""


async def insert_invalid_identifiers(conn: ConnectionLike, *, id_: int, column_3p_: str | None, new_notes: str) -> None:
    """Execute SQL query with `name: InsertInvalidIdentifiers :exec`.

    ```sql
    INSERT INTO test_invalid_identifiers (id, "3p%", "new notes") VALUES ($1, $2, $3)
    ```

    Args:
        conn:
            Connection object of type `ConnectionLike` used to execute the query.
        id_: int.
        column_3p_: str | None.
        new_notes: str.
    """
    await conn.execute(INSERT_INVALID_IDENTIFIERS, id_, column_3p_, new_notes)


async def get_invalid_identifiers(conn: ConnectionLike, *, id_: int) -> models.TestInvalidIdentifier | None:
    """Fetch one from the db using the SQL query with `name: GetInvalidIdentifiers :one`.

    ```sql
    SELECT id, "3p%", "new notes", "%pct" FROM test_invalid_identifiers WHERE id = $1
    ```

    Args:
        conn:
            Connection object of type `ConnectionLike` used to execute the query.
        id_: int.

    Returns:
        Result of type `models.TestInvalidIdentifier` fetched from the db. Will be `None` if not found.
    """
    row = await conn.fetchrow(GET_INVALID_IDENTIFIERS, id_)
    if row is None:
        return None
    return models.TestInvalidIdentifier(id_=row[0], column_3p_=row[1], new_notes=row[2], column__pct=row[3])


async def insert_third_party_stat(conn: ConnectionLike, *, id_: int, total: int) -> None:
    """Execute SQL query with `name: InsertThirdPartyStat :exec`.

    ```sql
    INSERT INTO "3rd_party_stats" (id, total) VALUES ($1, $2)
    ```

    Args:
        conn:
            Connection object of type `ConnectionLike` used to execute the query.
        id_: int.
        total: int.
    """
    await conn.execute(INSERT_THIRD_PARTY_STAT, id_, total)


async def get_third_party_stat(conn: ConnectionLike, *, id_: int) -> models.Model3RdPartyStat | None:
    """Fetch one from the db using the SQL query with `name: GetThirdPartyStat :one`.

    ```sql
    SELECT id, total FROM "3rd_party_stats" WHERE id = $1
    ```

    Args:
        conn:
            Connection object of type `ConnectionLike` used to execute the query.
        id_: int.

    Returns:
        Result of type `models.Model3RdPartyStat` fetched from the db. Will be `None` if not found.
    """
    row = await conn.fetchrow(GET_THIRD_PARTY_STAT, id_)
    if row is None:
        return None
    return models.Model3RdPartyStat(id_=row[0], total=row[1])
