# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.6.0
# source file: queries_field_namings.sql
"""Module containing queries from file queries_field_namings.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "GetJoinedFieldNamingsRow",
    "QueriesFieldNamings",
)

import psycopg
import psycopg.rows
import psycopg.types.string
import pydantic
import typing

if typing.TYPE_CHECKING:
    import collections.abc

    type ConnectionLike = psycopg.Connection[psycopg.rows.TupleRow]

from test.driver_psycopg_sync.pydantic.classes import models


psycopg.adapters.register_loader("jsonb", psycopg.types.string.TextLoader)


class GetJoinedFieldNamingsRow(pydantic.BaseModel):
    """Model representing GetJoinedFieldNamingsRow.

    Attributes:
        outputs: str
        outputs_2: str
    """

    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    outputs: str
    outputs_2: str


GET_FIELD_NAMING: typing.Final[typing.LiteralString] = """-- name: GetFieldNaming :one
SELECT id, outputs
FROM test_field_namings
WHERE id = %(p1)s LIMIT 1
"""

GET_JOINED_FIELD_NAMINGS: typing.Final[typing.LiteralString] = """-- name: GetJoinedFieldNamings :one
SELECT a.outputs, b.outputs
FROM test_field_namings a
JOIN test_field_namings b ON a.id = b.id
WHERE a.id = %(p1)s LIMIT 1
"""

SET_FIELD_NAMING_OUTPUTS: typing.Final[typing.LiteralString] = """-- name: SetFieldNamingOutputs :exec
UPDATE test_field_namings
SET outputs = %(p2)s
WHERE id = %(p1)s AND outputs <> %(p3)s::jsonb
"""


class QueriesFieldNamings:
    """Queries from file queries_field_namings.sql."""

    __slots__ = ("_conn",)

    def __init__(self, conn: ConnectionLike) -> None:
        """Initialize the instance using the connection.

        Args:
            conn:
                Connection object of type `ConnectionLike` used to execute the query.
        """
        self._conn = conn

    @property
    def conn(self) -> ConnectionLike:
        """Connection object used to make queries.

        Returns:
            Connection object of type `ConnectionLike` used to make queries.
        """
        return self._conn

    def get_field_naming(self, *, id_: int) -> models.TestFieldNaming | None:
        """Fetch one from the db using the SQL query with `name: GetFieldNaming :one`.

        ```sql
        SELECT id, outputs
        FROM test_field_namings
        WHERE id = %(p1)s LIMIT 1
        ```

        Args:
            id_: int.

        Returns:
            Result of type `models.TestFieldNaming` fetched from the db. Will be `None` if not found.
        """
        row = self._conn.execute(GET_FIELD_NAMING, {"p1": id_}).fetchone()
        if row is None:
            return None
        return models.TestFieldNaming(id_=row[0], outputs=row[1])

    def get_joined_field_namings(self, *, id_: int) -> GetJoinedFieldNamingsRow | None:
        """Fetch one from the db using the SQL query with `name: GetJoinedFieldNamings :one`.

        ```sql
        SELECT a.outputs, b.outputs
        FROM test_field_namings a
        JOIN test_field_namings b ON a.id = b.id
        WHERE a.id = %(p1)s LIMIT 1
        ```

        Args:
            id_: int.

        Returns:
            Result of type `GetJoinedFieldNamingsRow` fetched from the db. Will be `None` if not found.
        """
        row = self._conn.execute(GET_JOINED_FIELD_NAMINGS, {"p1": id_}).fetchone()
        if row is None:
            return None
        return GetJoinedFieldNamingsRow(outputs=row[0], outputs_2=row[1])

    def set_field_naming_outputs(self, *, id_: int, outputs: str, outputs_2: str) -> None:
        """Execute SQL query with `name: SetFieldNamingOutputs :exec`.

        ```sql
        UPDATE test_field_namings
        SET outputs = %(p2)s
        WHERE id = %(p1)s AND outputs <> %(p3)s::jsonb
        ```

        Args:
            id_: int.
            outputs: str.
            outputs_2: str.
        """
        self._conn.execute(SET_FIELD_NAMING_OUTPUTS, {"p1": id_, "p2": outputs, "p3": outputs_2})
