# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
#   sqlc-gen-better-python v0.4.6
# source file: queries_override_converter.sql
"""Module containing queries from file queries_override_converter.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = ("QueriesOverrideConverter",)

import datetime
import sqlite3
import typing

if typing.TYPE_CHECKING:
    import collections.abc


def _convert_datetime(val: bytes) -> datetime.datetime:
    return datetime.datetime.fromisoformat(val.decode())


sqlite3.register_converter("datetime", _convert_datetime)
sqlite3.register_converter("timestamp", _convert_datetime)


GET_OVERRIDE_HAPPENED_AT: typing.Final[str] = """-- name: GetOverrideHappenedAt :one
SELECT happened_at FROM test_override_conversion WHERE id = ?
"""


class QueriesOverrideConverter:
    """Queries from file queries_override_converter.sql."""

    __slots__ = ("_conn",)

    def __init__(self, conn: sqlite3.Connection) -> None:
        """Initialize the instance using the connection.

        Args:
            conn:
                Connection object of type `sqlite3.Connection` used to execute the query.
        """
        self._conn = conn

    @property
    def conn(self) -> sqlite3.Connection:
        """Connection object used to make queries.

        Returns:
            Connection object of type `sqlite3.Connection` used to make queries.
        """
        return self._conn

    def get_override_happened_at(self, *, id_: int) -> datetime.datetime | None:
        """Fetch one from the db using the SQL query with `name: GetOverrideHappenedAt :one`.

        ```sql
        SELECT happened_at FROM test_override_conversion WHERE id = ?
        ```

        Args:
            id_: int.

        Returns:
            Result of type `datetime.datetime` fetched from the db. Will be `None` if not found.
        """
        row = self._conn.execute(GET_OVERRIDE_HAPPENED_AT, (id_,)).fetchone()
        if row is None:
            return None
        return row[0]
