# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.5.1
# source file: queries_converters.sql
"""Module containing queries from file queries_converters.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "QueryResults",
    "delete_converted",
    "get_converted",
    "insert_converted",
    "list_converted_by_tags",
)

import operator
import test.converters
import typing

if typing.TYPE_CHECKING:
    from test.converters import Preferences
    import asyncpg
    import asyncpg.cursor
    import collections.abc

    type QueryResultsArgsType = int | float | str | memoryview | collections.abc.Sequence[QueryResultsArgsType] | None

    type ConnectionLike = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from test.driver_asyncpg.dataclass.functions import models


INSERT_CONVERTED: typing.Final[str] = """-- name: InsertConverted :exec
INSERT INTO test_converters (id, prefs, maybe_prefs, tags) VALUES ($1, $2, $3, $4)
"""

GET_CONVERTED: typing.Final[str] = """-- name: GetConverted :one
SELECT id, prefs, maybe_prefs, tags FROM test_converters WHERE id = $1
"""

LIST_CONVERTED_BY_TAGS: typing.Final[str] = """-- name: ListConvertedByTags :many
SELECT id FROM test_converters WHERE tags = $1
"""

DELETE_CONVERTED: typing.Final[str] = """-- name: DeleteConverted :exec
DELETE FROM test_converters WHERE id = $1
"""


class QueryResults[T]:
    """Helper class that allows both iteration and normal fetching of data from the db."""

    __slots__ = ("_args", "_conn", "_cursor", "_decode_hook", "_iterator", "_sql")

    def __init__(
        self,
        conn: ConnectionLike,
        sql: str,
        decode_hook: collections.abc.Callable[[asyncpg.Record], T],
        *args: QueryResultsArgsType,
    ) -> None:
        """Initialize the QueryResults instance.

        Args:
            conn:
                The connection object of type `ConnectionLike` used to execute queries.
            sql:
                The SQL statement that will be executed when fetching/iterating.
            decode_hook:
                A callback that turns an `asyncpg.Record` object into `T` that will be returned.
            *args:
                Arguments that should be sent when executing the sql query.
        """
        self._conn = conn
        self._sql = sql
        self._decode_hook = decode_hook
        self._args = args
        self._cursor: asyncpg.cursor.CursorFactory[asyncpg.Record] | None = None
        self._iterator: asyncpg.cursor.CursorIterator[asyncpg.Record] | None = None

    def __aiter__(self) -> QueryResults[T]:
        """Initialize iteration support for `async for`.

        Returns:
            Self as an asynchronous iterator.
        """
        return self

    def __await__(
        self,
    ) -> collections.abc.Generator[None, None, collections.abc.Sequence[T]]:
        """Allow `await` on the object to return all rows as a fully decoded sequence.

        Returns:
            A sequence of decoded objects of type `T`.
        """

        async def _wrapper() -> collections.abc.Sequence[T]:
            result = await self._conn.fetch(self._sql, *self._args)
            return [self._decode_hook(row) for row in result]

        return _wrapper().__await__()

    async def __anext__(self) -> T:
        """Yield the next item in the query result using an asyncpg cursor.

        Returns:
            The next decoded result of type `T`.

        Raises:
            StopAsyncIteration: When no more records are available.
        """
        if self._cursor is None or self._iterator is None:
            self._cursor = self._conn.cursor(self._sql, *self._args)
            self._iterator = self._cursor.__aiter__()
        try:
            record = await self._iterator.__anext__()
        except StopAsyncIteration:
            self._cursor = None
            self._iterator = None
            raise
        return self._decode_hook(record)


async def insert_converted(conn: ConnectionLike, *, id_: int, prefs: Preferences, maybe_prefs: Preferences | None, tags: frozenset[str]) -> None:
    """Execute SQL query with `name: InsertConverted :exec`.

    ```sql
    INSERT INTO test_converters (id, prefs, maybe_prefs, tags) VALUES ($1, $2, $3, $4)
    ```

    Args:
        conn:
            Connection object of type `ConnectionLike` used to execute the query.
        id_: int.
        prefs: Preferences.
        maybe_prefs: Preferences | None.
        tags: frozenset[str].
    """
    await conn.execute(INSERT_CONVERTED, id_, test.converters.encode_preferences(prefs), test.converters.encode_preferences(maybe_prefs) if maybe_prefs is not None else None, test.converters.encode_tags(tags))


async def get_converted(conn: ConnectionLike, *, id_: int) -> models.TestConverter | None:
    """Fetch one from the db using the SQL query with `name: GetConverted :one`.

    ```sql
    SELECT id, prefs, maybe_prefs, tags FROM test_converters WHERE id = $1
    ```

    Args:
        conn:
            Connection object of type `ConnectionLike` used to execute the query.
        id_: int.

    Returns:
        Result of type `models.TestConverter` fetched from the db. Will be `None` if not found.
    """
    row = await conn.fetchrow(GET_CONVERTED, id_)
    if row is None:
        return None
    return models.TestConverter(id_=row[0], prefs=test.converters.decode_preferences(row[1]), maybe_prefs=test.converters.decode_preferences(row[2]) if row[2] is not None else None, tags=test.converters.decode_tags(row[3]))


def list_converted_by_tags(conn: ConnectionLike, *, tags: frozenset[str]) -> QueryResults[int]:
    """Fetch many from the db using the SQL query with `name: ListConvertedByTags :many`.

    ```sql
    SELECT id FROM test_converters WHERE tags = $1
    ```

    Args:
        conn:
            Connection object of type `ConnectionLike` used to execute the query.
        tags: frozenset[str].

    Returns:
        Helper class of type `QueryResults[int]` that allows both iteration and normal fetching of data from the db.
    """
    return QueryResults(conn, LIST_CONVERTED_BY_TAGS, operator.itemgetter(0), test.converters.encode_tags(tags))


async def delete_converted(conn: ConnectionLike, *, id_: int) -> None:
    """Execute SQL query with `name: DeleteConverted :exec`.

    ```sql
    DELETE FROM test_converters WHERE id = $1
    ```

    Args:
        conn:
            Connection object of type `ConnectionLike` used to execute the query.
        id_: int.
    """
    await conn.execute(DELETE_CONVERTED, id_)
