# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
#   sqlc-gen-better-python v0.4.6
# source file: queries_invalid_identifiers.sql
"""Module containing queries from file queries_invalid_identifiers.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = ("QueriesInvalidIdentifiers",)

import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import collections.abc

    type ConnectionLike = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from test.driver_asyncpg.attrs.classes import models


INSERT_INVALID_IDENTIFIERS: typing.Final[str] = """-- name: InsertInvalidIdentifiers :exec
INSERT INTO test_invalid_identifiers (id, "3p%", "new notes") VALUES ($1, $2, $3)
"""

GET_INVALID_IDENTIFIERS: typing.Final[str] = """-- name: GetInvalidIdentifiers :one
SELECT id, "3p%", "new notes" FROM test_invalid_identifiers WHERE id = $1
"""


class QueriesInvalidIdentifiers:
    """Queries from file queries_invalid_identifiers.sql.

    Parameters
    ----------
    conn : ConnectionLike
        The connection object used to execute queries.

    """

    __slots__ = ("_conn",)

    def __init__(self, conn: ConnectionLike) -> None:
        """Initialize the instance using the connection."""
        self._conn = conn

    @property
    def conn(self) -> ConnectionLike:
        """Connection object used to make queries.

        Returns
        -------
        ConnectionLike

        """
        return self._conn

    async def insert_invalid_identifiers(self, *, id_: int, arg_3p_: str | None, new_notes: str) -> None:
        """Execute SQL query with `name: InsertInvalidIdentifiers :exec`.

        ```sql
        INSERT INTO test_invalid_identifiers (id, "3p%", "new notes") VALUES ($1, $2, $3)
        ```

        Parameters
        ----------
        id_ : int
        arg_3p_ : str | None
        new_notes : str

        """
        await self._conn.execute(INSERT_INVALID_IDENTIFIERS, id_, arg_3p_, new_notes)

    async def get_invalid_identifiers(self, *, id_: int) -> models.TestInvalidIdentifier | None:
        """Fetch one from the db using the SQL query with `name: GetInvalidIdentifiers :one`.

        ```sql
        SELECT id, "3p%", "new notes" FROM test_invalid_identifiers WHERE id = $1
        ```

        Parameters
        ----------
        id_ : int

        Returns
        -------
        models.TestInvalidIdentifier
            Result fetched from the db. Will be `None` if not found.

        """
        row = await self._conn.fetchrow(GET_INVALID_IDENTIFIERS, id_)
        if row is None:
            return None
        return models.TestInvalidIdentifier(id_=row[0], column_3p_=row[1], new_notes=row[2])
