# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.5.0
"""Module containing models."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = ("TestEnumOverride",)

import dataclasses
import collections.abc


@dataclasses.dataclass()
class TestEnumOverride:
    """Model representing TestEnumOverride.

    Attributes:
        id_: int
        mood_test: str
    """

    id_: int
    mood_test: str
