# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.8.0
"""Module containing models."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "TestInnerMysqlType",
    "TestMysqlType",
    "TestReservedArg",
    "TestTypeOverride",
)

from collections import UserString
import datetime
import decimal
import pydantic
import typing

if typing.TYPE_CHECKING:
    import collections.abc

from test.driver_asyncmy.pydantic.functions import enums


class TestInnerMysqlType(pydantic.BaseModel):
    """Model representing TestInnerMysqlType.

    Attributes:
        table_id: int
        int_test: int | None
        integer_test: int | None
        mediumint_test: int | None
        smallint_test: int | None
        tinyint_test: int | None
        bigint_test: int | None
        int_unsigned_test: int | None
        bigint_unsigned_test: int | None
        year_test: int | None
        tinyint1_test: bool | None
        bool_test: bool | None
        boolean_test: bool | None
        float_test: float | None
        double_test: float | None
        double_precision_test: float | None
        real_test: float | None
        decimal_test: decimal.Decimal | None
        numeric_test: decimal.Decimal | None
        char_test: str | None
        varchar_test: str | None
        tinytext_test: str | None
        text_test: str | None
        mediumtext_test: str | None
        longtext_test: str | None
        binary_test: memoryview | None
        varbinary_test: memoryview | None
        tinyblob_test: memoryview | None
        blob_test: memoryview | None
        mediumblob_test: memoryview | None
        longblob_test: memoryview | None
        bit_test: memoryview | None
        date_test: datetime.date | None
        datetime_test: datetime.datetime | None
        datetime6_test: datetime.datetime | None
        timestamp_test: datetime.datetime | None
        time_test: datetime.timedelta | None
        json_test: str | None
        mood: enums.TestInnerMysqlTypesMood | None
        tag: enums.TestInnerMysqlTypesTag | None
    """

    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    table_id: int
    int_test: int | None
    integer_test: int | None
    mediumint_test: int | None
    smallint_test: int | None
    tinyint_test: int | None
    bigint_test: int | None
    int_unsigned_test: int | None
    bigint_unsigned_test: int | None
    year_test: int | None
    tinyint1_test: bool | None
    bool_test: bool | None
    boolean_test: bool | None
    float_test: float | None
    double_test: float | None
    double_precision_test: float | None
    real_test: float | None
    decimal_test: decimal.Decimal | None
    numeric_test: decimal.Decimal | None
    char_test: str | None
    varchar_test: str | None
    tinytext_test: str | None
    text_test: str | None
    mediumtext_test: str | None
    longtext_test: str | None
    binary_test: memoryview | None
    varbinary_test: memoryview | None
    tinyblob_test: memoryview | None
    blob_test: memoryview | None
    mediumblob_test: memoryview | None
    longblob_test: memoryview | None
    bit_test: memoryview | None
    date_test: datetime.date | None
    datetime_test: datetime.datetime | None
    datetime6_test: datetime.datetime | None
    timestamp_test: datetime.datetime | None
    time_test: datetime.timedelta | None
    json_test: str | None
    mood: enums.TestInnerMysqlTypesMood | None
    tag: enums.TestInnerMysqlTypesTag | None


class TestMysqlType(pydantic.BaseModel):
    """Model representing TestMysqlType.

    Attributes:
        id_: int
        int_test: int
        integer_test: int
        mediumint_test: int
        smallint_test: int
        tinyint_test: int
        bigint_test: int
        int_unsigned_test: int
        bigint_unsigned_test: int
        year_test: int
        tinyint1_test: bool
        bool_test: bool
        boolean_test: bool
        float_test: float
        double_test: float
        double_precision_test: float
        real_test: float
        decimal_test: decimal.Decimal
        numeric_test: decimal.Decimal
        char_test: str
        varchar_test: str
        tinytext_test: str
        text_test: str
        mediumtext_test: str
        longtext_test: str
        binary_test: memoryview
        varbinary_test: memoryview
        tinyblob_test: memoryview
        blob_test: memoryview
        mediumblob_test: memoryview
        longblob_test: memoryview
        bit_test: memoryview
        date_test: datetime.date
        datetime_test: datetime.datetime
        datetime6_test: datetime.datetime
        timestamp_test: datetime.datetime
        time_test: datetime.timedelta
        json_test: str
        mood: enums.TestMysqlTypesMood
        tag: enums.TestMysqlTypesTag
    """

    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    int_test: int
    integer_test: int
    mediumint_test: int
    smallint_test: int
    tinyint_test: int
    bigint_test: int
    int_unsigned_test: int
    bigint_unsigned_test: int
    year_test: int
    tinyint1_test: bool
    bool_test: bool
    boolean_test: bool
    float_test: float
    double_test: float
    double_precision_test: float
    real_test: float
    decimal_test: decimal.Decimal
    numeric_test: decimal.Decimal
    char_test: str
    varchar_test: str
    tinytext_test: str
    text_test: str
    mediumtext_test: str
    longtext_test: str
    binary_test: memoryview
    varbinary_test: memoryview
    tinyblob_test: memoryview
    blob_test: memoryview
    mediumblob_test: memoryview
    longblob_test: memoryview
    bit_test: memoryview
    date_test: datetime.date
    datetime_test: datetime.datetime
    datetime6_test: datetime.datetime
    timestamp_test: datetime.datetime
    time_test: datetime.timedelta
    json_test: str
    mood: enums.TestMysqlTypesMood
    tag: enums.TestMysqlTypesTag


class TestReservedArg(pydantic.BaseModel):
    """Model representing TestReservedArg.

    Attributes:
        id_: int
        conn: str
    """

    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    conn: str


class TestTypeOverride(pydantic.BaseModel):
    """Model representing TestTypeOverride.

    Attributes:
        id_: int
        text_test: UserString | None
    """

    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    text_test: UserString | None
