# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
#   sqlc-gen-better-python v0.4.6
# source file: queries_enum_override.sql
"""Module containing queries from file queries_enum_override.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = ("QueriesEnumOverride",)

import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import collections.abc

    ConnectionLike: typing.TypeAlias = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from test.driver_asyncpg.dataclass.classes import enums


INSERT_ENUM_OVERRIDE: typing.Final[str] = """-- name: InsertEnumOverride :exec
INSERT INTO test_enum_override (id, mood_test) VALUES ($1, $2)
"""

GET_ENUM_OVERRIDE_MOOD: typing.Final[str] = """-- name: GetEnumOverrideMood :one
SELECT mood_test FROM test_enum_override WHERE id = $1
"""


class QueriesEnumOverride:
    """Queries from file queries_enum_override.sql."""

    __slots__ = ("_conn",)

    def __init__(self, conn: ConnectionLike) -> None:
        """Initialize the instance using the connection.

        Args:
            conn:
                Connection object of type `ConnectionLike` used to execute the query.
        """
        self._conn = conn

    @property
    def conn(self) -> ConnectionLike:
        """Connection object used to make queries.

        Returns:
            Connection object of type `ConnectionLike` used to make queries.
        """
        return self._conn

    async def insert_enum_override(self, *, id_: int, mood_test: str) -> None:
        """Execute SQL query with `name: InsertEnumOverride :exec`.

        ```sql
        INSERT INTO test_enum_override (id, mood_test) VALUES ($1, $2)
        ```

        Args:
            id_: int.
            mood_test: str.
        """
        await self._conn.execute(INSERT_ENUM_OVERRIDE, id_, enums.TestMood(mood_test))

    async def get_enum_override_mood(self, *, id_: int) -> str | None:
        """Fetch one from the db using the SQL query with `name: GetEnumOverrideMood :one`.

        ```sql
        SELECT mood_test FROM test_enum_override WHERE id = $1
        ```

        Args:
            id_: int.

        Returns:
            Result of type `str` fetched from the db. Will be `None` if not found.
        """
        row = await self._conn.fetchrow(GET_ENUM_OVERRIDE_MOOD, id_)
        if row is None:
            return None
        return str(row[0])
