# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.6.0
# source file: queries_field_namings.sql
"""Module containing queries from file queries_field_namings.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "GetJoinedFieldNamingsRow",
    "QueriesFieldNamings",
)

import dataclasses
import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import collections.abc

    type ConnectionLike = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from test.driver_asyncpg.dataclass.classes import models


@dataclasses.dataclass()
class GetJoinedFieldNamingsRow:
    """Model representing GetJoinedFieldNamingsRow.

    Attributes:
        outputs: str
        outputs_2: str
    """

    outputs: str
    outputs_2: str


GET_FIELD_NAMING: typing.Final[str] = """-- name: GetFieldNaming :one
SELECT id, outputs
FROM test_field_namings
WHERE id = $1 LIMIT 1
"""

GET_JOINED_FIELD_NAMINGS: typing.Final[str] = """-- name: GetJoinedFieldNamings :one
SELECT a.outputs, b.outputs
FROM test_field_namings a
JOIN test_field_namings b ON a.id = b.id
WHERE a.id = $1 LIMIT 1
"""

SET_FIELD_NAMING_OUTPUTS: typing.Final[str] = """-- name: SetFieldNamingOutputs :exec
UPDATE test_field_namings
SET outputs = $2
WHERE id = $1 AND outputs <> $3::jsonb
"""


class QueriesFieldNamings:
    """Queries from file queries_field_namings.sql."""

    __slots__ = ("_conn",)

    def __init__(self, conn: ConnectionLike) -> None:
        """Initialize the instance using the connection.

        Args:
            conn:
                Connection object of type `ConnectionLike` used to execute the query.
        """
        self._conn = conn

    @property
    def conn(self) -> ConnectionLike:
        """Connection object used to make queries.

        Returns:
            Connection object of type `ConnectionLike` used to make queries.
        """
        return self._conn

    async def get_field_naming(self, *, id_: int) -> models.TestFieldNaming | None:
        """Fetch one from the db using the SQL query with `name: GetFieldNaming :one`.

        ```sql
        SELECT id, outputs
        FROM test_field_namings
        WHERE id = $1 LIMIT 1
        ```

        Args:
            id_: int.

        Returns:
            Result of type `models.TestFieldNaming` fetched from the db. Will be `None` if not found.
        """
        row = await self._conn.fetchrow(GET_FIELD_NAMING, id_)
        if row is None:
            return None
        return models.TestFieldNaming(id_=row[0], outputs=row[1])

    async def get_joined_field_namings(self, *, id_: int) -> GetJoinedFieldNamingsRow | None:
        """Fetch one from the db using the SQL query with `name: GetJoinedFieldNamings :one`.

        ```sql
        SELECT a.outputs, b.outputs
        FROM test_field_namings a
        JOIN test_field_namings b ON a.id = b.id
        WHERE a.id = $1 LIMIT 1
        ```

        Args:
            id_: int.

        Returns:
            Result of type `GetJoinedFieldNamingsRow` fetched from the db. Will be `None` if not found.
        """
        row = await self._conn.fetchrow(GET_JOINED_FIELD_NAMINGS, id_)
        if row is None:
            return None
        return GetJoinedFieldNamingsRow(outputs=row[0], outputs_2=row[1])

    async def set_field_naming_outputs(self, *, id_: int, outputs: str, outputs_2: str) -> None:
        """Execute SQL query with `name: SetFieldNamingOutputs :exec`.

        ```sql
        UPDATE test_field_namings
        SET outputs = $2
        WHERE id = $1 AND outputs <> $3::jsonb
        ```

        Args:
            id_: int.
            outputs: str.
            outputs_2: str.
        """
        await self._conn.execute(SET_FIELD_NAMING_OUTPUTS, id_, outputs, outputs_2)
