# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
#   sqlc-gen-better-python v0.4.4
"""Package containing queries and models automatically generated using sqlc-gen-better-python."""
