# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.5.1
# source file: queries_override_converter.sql
"""Module containing queries from file queries_override_converter.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = ("QueriesOverrideConverter",)

import ciso8601
import sqlite3
import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import datetime


def _convert_datetime(val: bytes) -> datetime.datetime:
    return ciso8601.parse_datetime(val.decode())


sqlite3.register_converter("datetime", _convert_datetime)
sqlite3.register_converter("timestamp", _convert_datetime)


GET_OVERRIDE_HAPPENED_AT: typing.Final[str] = """-- name: GetOverrideHappenedAt :one
SELECT happened_at FROM test_override_conversion WHERE id = ?
"""


class QueriesOverrideConverter:
    """Queries from file queries_override_converter.sql.

    Parameters
    ----------
    conn : sqlite3.Connection
        The connection object used to execute queries.

    """

    __slots__ = ("_conn",)

    def __init__(self, conn: sqlite3.Connection) -> None:
        """Initialize the instance using the connection."""
        self._conn = conn

    @property
    def conn(self) -> sqlite3.Connection:
        """Connection object used to make queries.

        Returns
        -------
        sqlite3.Connection

        """
        return self._conn

    def get_override_happened_at(self, *, id_: int) -> datetime.datetime | None:
        """Fetch one from the db using the SQL query with `name: GetOverrideHappenedAt :one`.

        ```sql
        SELECT happened_at FROM test_override_conversion WHERE id = ?
        ```

        Parameters
        ----------
        id_ : int

        Returns
        -------
        datetime.datetime
            Result fetched from the db. Will be `None` if not found.

        """
        row = self._conn.execute(GET_OVERRIDE_HAPPENED_AT, (id_,)).fetchone()
        if row is None:
            return None
        return row[0]
