# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.5.1
# source file: queries_override_adapter.sql
"""Module containing queries from file queries_override_adapter.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = ("QueriesOverrideAdapter",)

import datetime
import decimal
import sqlite3
import typing

if typing.TYPE_CHECKING:
    import collections.abc


def _adapt_decimal(val: decimal.Decimal) -> str:
    return str(val)


def _adapt_datetime(val: datetime.datetime) -> str:
    return val.isoformat()


sqlite3.register_adapter(decimal.Decimal, _adapt_decimal)
sqlite3.register_adapter(datetime.datetime, _adapt_datetime)


INSERT_OVERRIDE_CONVERSION: typing.Final[str] = """-- name: InsertOverrideConversion :exec
INSERT INTO test_override_conversion (id, price, happened_at) VALUES (?, ?, ?)
"""

GET_OVERRIDE_PRICE: typing.Final[str] = """-- name: GetOverridePrice :one
SELECT price FROM test_override_conversion WHERE id = ?
"""


class QueriesOverrideAdapter:
    """Queries from file queries_override_adapter.sql.

    Parameters
    ----------
    conn : sqlite3.Connection
        The connection object used to execute queries.

    """

    __slots__ = ("_conn",)

    def __init__(self, conn: sqlite3.Connection) -> None:
        """Initialize the instance using the connection."""
        self._conn = conn

    @property
    def conn(self) -> sqlite3.Connection:
        """Connection object used to make queries.

        Returns
        -------
        sqlite3.Connection

        """
        return self._conn

    def insert_override_conversion(self, *, id_: int, price: float, happened_at: datetime.datetime) -> None:
        """Execute SQL query with `name: InsertOverrideConversion :exec`.

        ```sql
        INSERT INTO test_override_conversion (id, price, happened_at) VALUES (?, ?, ?)
        ```

        Parameters
        ----------
        id_ : int
        price : float
        happened_at : datetime.datetime

        """
        self._conn.execute(INSERT_OVERRIDE_CONVERSION, (id_, decimal.Decimal(price), happened_at))

    def get_override_price(self, *, id_: int) -> float | None:
        """Fetch one from the db using the SQL query with `name: GetOverridePrice :one`.

        ```sql
        SELECT price FROM test_override_conversion WHERE id = ?
        ```

        Parameters
        ----------
        id_ : int

        Returns
        -------
        float
            Result fetched from the db. Will be `None` if not found.

        """
        row = self._conn.execute(GET_OVERRIDE_PRICE, (id_,)).fetchone()
        if row is None:
            return None
        return float(row[0])
