# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
#   sqlc-gen-better-python v0.4.6
# source file: queries_override_adapter.sql
"""Module containing queries from file queries_override_adapter.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "get_override_price",
    "insert_override_conversion",
)

import datetime
import decimal
import sqlite3
import typing

if typing.TYPE_CHECKING:
    import collections.abc


def _adapt_decimal(val: decimal.Decimal) -> str:
    return str(val)


def _adapt_datetime(val: datetime.datetime) -> str:
    return val.isoformat()


sqlite3.register_adapter(decimal.Decimal, _adapt_decimal)
sqlite3.register_adapter(datetime.datetime, _adapt_datetime)


INSERT_OVERRIDE_CONVERSION: typing.Final[str] = """-- name: InsertOverrideConversion :exec
INSERT INTO test_override_conversion (id, price, happened_at) VALUES (?, ?, ?)
"""

GET_OVERRIDE_PRICE: typing.Final[str] = """-- name: GetOverridePrice :one
SELECT price FROM test_override_conversion WHERE id = ?
"""


def insert_override_conversion(conn: sqlite3.Connection, *, id_: int, price: float, happened_at: datetime.datetime) -> None:
    """Execute SQL query with `name: InsertOverrideConversion :exec`.

    ```sql
    INSERT INTO test_override_conversion (id, price, happened_at) VALUES (?, ?, ?)
    ```

    Parameters
    ----------
    conn : sqlite3.Connection
        Connection object of type `sqlite3.Connection` used to execute the query.
    id_ : int
    price : float
    happened_at : datetime.datetime

    """
    conn.execute(INSERT_OVERRIDE_CONVERSION, (id_, decimal.Decimal(price), happened_at))


def get_override_price(conn: sqlite3.Connection, *, id_: int) -> float | None:
    """Fetch one from the db using the SQL query with `name: GetOverridePrice :one`.

    ```sql
    SELECT price FROM test_override_conversion WHERE id = ?
    ```

    Parameters
    ----------
    conn : sqlite3.Connection
        Connection object of type `sqlite3.Connection` used to execute the query.
    id_ : int

    Returns
    -------
    float
        Result fetched from the db. Will be `None` if not found.

    """
    row = conn.execute(GET_OVERRIDE_PRICE, (id_,)).fetchone()
    if row is None:
        return None
    return float(row[0])
