# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.6.0
# source file: queries_case.sql
"""Module containing queries from file queries_case.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "GetCaseRowRow",
    "get_case_row",
    "get_reserved_arg",
    "insert_case_row",
    "insert_reserved_arg",
)

import attrs
import datetime
import decimal
import sqlite3
import typing

if typing.TYPE_CHECKING:
    import collections.abc


def _adapt_decimal(val: decimal.Decimal) -> str:
    return str(val)


def _convert_decimal(val: bytes) -> decimal.Decimal:
    return decimal.Decimal(val.decode())


def _adapt_datetime(val: datetime.datetime) -> str:
    return val.isoformat()


def _convert_datetime(val: bytes) -> datetime.datetime:
    return datetime.datetime.fromisoformat(val.decode())


sqlite3.register_adapter(decimal.Decimal, _adapt_decimal)
sqlite3.register_adapter(datetime.datetime, _adapt_datetime)

sqlite3.register_converter("decimal", _convert_decimal)
sqlite3.register_converter("datetime", _convert_datetime)
sqlite3.register_converter("timestamp", _convert_datetime)


@attrs.define()
class GetCaseRowRow:
    """Model representing GetCaseRowRow.

    Attributes
    ----------
    upper_dt : datetime.datetime
    prec_dec : decimal.Decimal

    """

    upper_dt: datetime.datetime
    prec_dec: decimal.Decimal


INSERT_CASE_ROW: typing.Final[str] = """-- name: InsertCaseRow :exec
INSERT INTO test_case_sensitivity (id, upper_dt, prec_dec) VALUES (?, ?, ?)
"""

GET_CASE_ROW: typing.Final[str] = """-- name: GetCaseRow :one
SELECT upper_dt, prec_dec FROM test_case_sensitivity WHERE id = ?
"""

INSERT_RESERVED_ARG: typing.Final[str] = """-- name: InsertReservedArg :exec
INSERT INTO test_reserved_args (id, conn) VALUES (?, ?)
"""

GET_RESERVED_ARG: typing.Final[str] = """-- name: GetReservedArg :one
SELECT id FROM test_reserved_args WHERE conn = ?
"""


def insert_case_row(conn: sqlite3.Connection, *, id_: int, upper_dt: datetime.datetime, prec_dec: decimal.Decimal) -> None:
    """Execute SQL query with `name: InsertCaseRow :exec`.

    ```sql
    INSERT INTO test_case_sensitivity (id, upper_dt, prec_dec) VALUES (?, ?, ?)
    ```

    Parameters
    ----------
    conn : sqlite3.Connection
        Connection object of type `sqlite3.Connection` used to execute the query.
    id_ : int
    upper_dt : datetime.datetime
    prec_dec : decimal.Decimal

    """
    conn.execute(INSERT_CASE_ROW, (id_, upper_dt, prec_dec))


def get_case_row(conn: sqlite3.Connection, *, id_: int) -> GetCaseRowRow | None:
    """Fetch one from the db using the SQL query with `name: GetCaseRow :one`.

    ```sql
    SELECT upper_dt, prec_dec FROM test_case_sensitivity WHERE id = ?
    ```

    Parameters
    ----------
    conn : sqlite3.Connection
        Connection object of type `sqlite3.Connection` used to execute the query.
    id_ : int

    Returns
    -------
    GetCaseRowRow
        Result fetched from the db. Will be `None` if not found.

    """
    row = conn.execute(GET_CASE_ROW, (id_,)).fetchone()
    if row is None:
        return None
    return GetCaseRowRow(upper_dt=row[0], prec_dec=row[1])


def insert_reserved_arg(conn: sqlite3.Connection, *, id_: int, conn_2: str) -> None:
    """Execute SQL query with `name: InsertReservedArg :exec`.

    ```sql
    INSERT INTO test_reserved_args (id, conn) VALUES (?, ?)
    ```

    Parameters
    ----------
    conn : sqlite3.Connection
        Connection object of type `sqlite3.Connection` used to execute the query.
    id_ : int
    conn_2 : str

    """
    conn.execute(INSERT_RESERVED_ARG, (id_, conn_2))


def get_reserved_arg(conn: sqlite3.Connection, *, conn_2: str) -> int | None:
    """Fetch one from the db using the SQL query with `name: GetReservedArg :one`.

    ```sql
    SELECT id FROM test_reserved_args WHERE conn = ?
    ```

    Parameters
    ----------
    conn : sqlite3.Connection
        Connection object of type `sqlite3.Connection` used to execute the query.
    conn_2 : str

    Returns
    -------
    int
        Result fetched from the db. Will be `None` if not found.

    """
    row = conn.execute(GET_RESERVED_ARG, (conn_2,)).fetchone()
    if row is None:
        return None
    return row[0]
